//! Mixer floating window — mirrors the Futureboard WebUI MixerPanel exactly.
//!
//! Key measurements from MixerPanel.tsx / theme.ts:
//!   strip width       72px (we use 76 for a comfortable egui layout)
//!   button height     20px, 9px Inter
//!   accent bar        1.5px top of each strip
//!   pan knob          40px diameter arc
//!   fader rail        3px wide
//!   meter columns     5px × 2 (stereo), 20 segments, 1.5px gap
//!   dB scale labels   7.5px at 0/-6/-12/-18/-24/-36/-54/-∞

#![allow(deprecated)]

use crossbeam_channel::Sender;
use egui::{Align2, Color32, FontId, FontFamily, Pos2, Rect, RichText, Sense, Stroke, Ui, Vec2};
use serde_json::json;

use crate::protocol::{MixerMaster, MixerTrack, OutgoingMessage};
use crate::theme::{self, db_str, db_to_linear, parse_hex};

const STRIP_W: f32 = 76.0;
const STRIP_MIN_H: f32 = 290.0;
const BTN_H: f32 = 20.0;
const METER_W: f32 = 5.0; // per channel (L or R)
const METER_GAP: f32 = 2.0; // between L and R meter
const FADER_W: f32 = 18.0;
const ACCENT_BAR_H: f32 = 2.0;

// dB scale marks (top to bottom on fader: 0 → -∞)
const DB_MARKS: &[f32] = &[0.0, -6.0, -12.0, -18.0, -24.0, -36.0, -54.0];

pub struct MixerWindow {
    pub tracks: Vec<MixerTrack>,
    pub master: Option<MixerMaster>,
}

impl MixerWindow {
    pub fn new() -> Self {
        Self { tracks: Vec::new(), master: None }
    }

    pub fn update_tracks(&mut self, tracks: Vec<MixerTrack>, master: Option<MixerMaster>) {
        self.tracks = tracks;
        self.master = master;
    }

    pub fn show(&mut self, ctx: &egui::Context, out_tx: &Sender<OutgoingMessage>, _win_id: &str) {
        egui::CentralPanel::default()
            .frame(egui::Frame {
                fill: theme::BG,
                inner_margin: egui::Margin::same(0),
                ..Default::default()
            })
            .show(ctx, |ui| {
                // ── toolbar ───────────────────────────────────────────────────
                egui::Frame {
                    fill: theme::SURFACE,
                    inner_margin: egui::Margin { left: 10, right: 10, top: 6, bottom: 6 },
                    ..Default::default()
                }
                .show(ui, |ui| {
                    ui.horizontal(|ui| {
                        ui.label(theme::header_rt("MIXER"));
                        ui.add_space(6.0);
                        ui.label(
                            RichText::new(if self.tracks.is_empty() {
                                "Waiting for project…".into()
                            } else {
                                format!("{} tracks", self.tracks.len())
                            })
                            .size(9.0)
                            .color(theme::FAINT),
                        );
                    });
                });

                ui.add_space(1.0);

                // ── strips ────────────────────────────────────────────────────
                egui::ScrollArea::horizontal()
                    .auto_shrink([false, false])
                    .show(ui, |ui| {
                        ui.horizontal(|ui| {
                            ui.spacing_mut().item_spacing.x = 1.0;

                            let cmds = draw_strips(ui, &mut self.tracks, &self.master);
                            for cmd in cmds {
                                let _ = out_tx.send(cmd);
                            }
                        });
                    });
            });
    }
}

impl Default for MixerWindow {
    fn default() -> Self { Self::new() }
}

// ── strip drawing ─────────────────────────────────────────────────────────────

fn draw_strips(
    ui: &mut Ui,
    tracks: &mut Vec<MixerTrack>,
    master: &Option<MixerMaster>,
) -> Vec<OutgoingMessage> {
    let mut cmds = Vec::new();
    for track in tracks.iter_mut() {
        cmds.extend(draw_track_strip(ui, track));
    }
    if let Some(m) = master {
        draw_master_strip(ui, m);
    }
    cmds
}

/// One channel strip.  Returns any commands generated by user interaction.
fn draw_track_strip(ui: &mut Ui, track: &mut MixerTrack) -> Vec<OutgoingMessage> {
    let mut cmds = Vec::new();
    let track_color = parse_hex(&track.color);

    egui::Frame {
        fill: theme::SURFACE,
        inner_margin: egui::Margin::same(0),
        ..Default::default()
    }
    .show(ui, |ui| {
        ui.set_width(STRIP_W);
        ui.set_min_height(STRIP_MIN_H);

        ui.vertical(|ui| {
            // ── accent color bar ──────────────────────────────────────────────
            let (bar_rect, _) =
                ui.allocate_exact_size(Vec2::new(STRIP_W, ACCENT_BAR_H), Sense::hover());
            ui.painter().rect_filled(bar_rect, 0.0, track_color);

            // ── track name ────────────────────────────────────────────────────
            egui::Frame {
                fill: theme::SURFACE_HIGH,
                inner_margin: egui::Margin { left: 6, right: 6, top: 4, bottom: 4 },
                ..Default::default()
            }
            .show(ui, |ui| {
                ui.set_width(STRIP_W - ACCENT_BAR_H); // no extra margin needed
                ui.label(
                    RichText::new(&track.name)
                        .font(FontId::new(10.5, FontFamily::Proportional))
                        .color(theme::TEXT)
                        .strong(),
                );
            });

            let inner_margin = egui::Margin { left: 6, right: 6, top: 6, bottom: 6 };

            egui::Frame {
                fill: theme::SURFACE,
                inner_margin,
                ..Default::default()
            }
            .show(ui, |ui| {
                ui.set_width(STRIP_W);
                ui.spacing_mut().item_spacing = Vec2::new(2.0, 3.0);
                ui.vertical_centered(|ui| {
                    // ── M / S / A buttons ─────────────────────────────────────
                    ui.horizontal(|ui| {
                        ui.spacing_mut().item_spacing.x = 2.0;
                        let id = track.id.clone();

                        // Mute
                        let (m_fill, m_text_color) = if track.mute {
                            (theme::YELLOW, theme::SUNKEN)
                        } else {
                            (theme::SURFACE_HIGH, theme::DIM)
                        };
                        if ui
                            .add_sized(
                                [20.0, BTN_H],
                                egui::Button::new(
                                    RichText::new("M").size(9.0).color(m_text_color),
                                )
                                .fill(m_fill),
                            )
                            .clicked()
                        {
                            track.mute = !track.mute;
                            cmds.push(cmd("mixer.setMute", json!({ "trackId": id, "mute": track.mute })));
                        }

                        // Solo
                        let (s_fill, s_text_color) = if track.solo {
                            (theme::GREEN, theme::SUNKEN)
                        } else {
                            (theme::SURFACE_HIGH, theme::DIM)
                        };
                        if ui
                            .add_sized(
                                [20.0, BTN_H],
                                egui::Button::new(
                                    RichText::new("S").size(9.0).color(s_text_color),
                                )
                                .fill(s_fill),
                            )
                            .clicked()
                        {
                            track.solo = !track.solo;
                            cmds.push(cmd("mixer.setSolo", json!({ "trackId": id, "solo": track.solo })));
                        }

                        // Arm
                        let (a_fill, a_text_color) = if track.armed {
                            (theme::RED, theme::SUNKEN)
                        } else {
                            (theme::SURFACE_HIGH, theme::DIM)
                        };
                        if ui
                            .add_sized(
                                [20.0, BTN_H],
                                egui::Button::new(
                                    RichText::new("A").size(9.0).color(a_text_color),
                                )
                                .fill(a_fill),
                            )
                            .clicked()
                        {
                            track.armed = !track.armed;
                            cmds.push(cmd("mixer.setArm", json!({ "trackId": id, "armed": track.armed })));
                        }
                    });

                    ui.add_space(4.0);

                    // ── dB readout ────────────────────────────────────────────
                    ui.label(
                        RichText::new(db_str(track.volume))
                            .size(10.0)
                            .color(theme::TEXT_SOFT)
                            .font(FontId::new(10.0, FontFamily::Monospace)),
                    );

                    ui.add_space(2.0);

                    // ── fader + dB scale + stereo meter ───────────────────────
                    ui.horizontal(|ui| {
                        ui.spacing_mut().item_spacing.x = 3.0;

                        // dB scale (left of fader)
                        draw_db_scale(ui, 120.0, theme::FAINT);

                        // Vertical fader
                        let fader_response = ui.add_sized(
                            [FADER_W, 120.0],
                            egui::Slider::new(&mut track.volume, 0.0..=1.5)
                                .vertical()
                                .show_value(false),
                        );
                        if fader_response.changed() {
                            cmds.push(cmd(
                                "mixer.setVolume",
                                json!({ "trackId": track.id, "volume": track.volume }),
                            ));
                        }

                        ui.add_space(2.0);

                        // Stereo VU meter
                        ui.vertical(|ui| {
                            ui.spacing_mut().item_spacing.y = METER_GAP;
                            theme::draw_vu_meter(ui, track.meter_l, METER_W, 120.0);
                            theme::draw_vu_meter(ui, track.meter_r, METER_W, 120.0);
                        });
                    });

                    ui.add_space(4.0);

                    // ── pan arc ───────────────────────────────────────────────
                    ui.label(theme::header_rt("PAN"));
                    let pan_resp = ui.add(
                        egui::Slider::new(&mut track.pan, -1.0..=1.0)
                            .show_value(false),
                    );
                    if pan_resp.changed() {
                        cmds.push(cmd(
                            "mixer.setPan",
                            json!({ "trackId": track.id, "pan": track.pan }),
                        ));
                    }

                    let pan_pct = (track.pan * 100.0) as i32;
                    ui.label(
                        RichText::new(if pan_pct == 0 {
                            "C".into()
                        } else if pan_pct > 0 {
                            format!("R{}", pan_pct)
                        } else {
                            format!("L{}", -pan_pct)
                        })
                        .size(8.0)
                        .color(theme::DIM),
                    );

                    ui.add_space(4.0);

                    // ── inserts placeholder ───────────────────────────────────
                    section_header(ui, "INSERTS");
                    placeholder_slot(ui, Color32::from_rgba_unmultiplied(0x5F, 0xCE, 0xD0, 30));

                    // ── sends placeholder ─────────────────────────────────────
                    section_header(ui, "SENDS");
                    placeholder_slot(ui, Color32::from_rgba_unmultiplied(0xFF, 0xFF, 0xFF, 8));
                });
            });
        });
    });

    cmds
}

fn draw_master_strip(ui: &mut Ui, master: &MixerMaster) {
    egui::Frame {
        fill: theme::SURFACE_HIGH,
        stroke: Stroke::new(1.0, theme::ACCENT),
        inner_margin: egui::Margin::same(0),
        ..Default::default()
    }
    .show(ui, |ui| {
        ui.set_width(STRIP_W);
        ui.set_min_height(STRIP_MIN_H);

        ui.vertical(|ui| {
            // Accent bar — cyan for master
            let (bar_rect, _) =
                ui.allocate_exact_size(Vec2::new(STRIP_W, ACCENT_BAR_H), Sense::hover());
            ui.painter().rect_filled(bar_rect, 0.0, theme::ACCENT);

            // Label
            egui::Frame {
                fill: theme::SURFACE_ACTIVE,
                inner_margin: egui::Margin { left: 6, right: 6, top: 4, bottom: 4 },
                ..Default::default()
            }
            .show(ui, |ui| {
                ui.set_width(STRIP_W);
                ui.label(
                    RichText::new("MASTER")
                        .size(10.5)
                        .color(theme::ACCENT)
                        .strong(),
                );
            });

            egui::Frame {
                fill: theme::SURFACE_HIGH,
                inner_margin: egui::Margin { left: 6, right: 6, top: 6, bottom: 6 },
                ..Default::default()
            }
            .show(ui, |ui| {
                ui.set_width(STRIP_W);
                ui.vertical_centered(|ui| {
                    ui.label(
                        RichText::new(db_str(master.volume))
                            .size(10.0)
                            .color(theme::ACCENT)
                            .font(FontId::new(10.0, FontFamily::Monospace)),
                    );
                    ui.add_space(6.0);
                    ui.horizontal(|ui| {
                        ui.spacing_mut().item_spacing.x = 3.0;
                        draw_db_scale(ui, 120.0, theme::FAINT);
                        // Read-only fader placeholder
                        let pos = 1.0 - master.volume.clamp(0.0, 1.5) / 1.5;
                        draw_static_fader(ui, pos, FADER_W, 120.0);
                        ui.add_space(2.0);
                        ui.vertical(|ui| {
                            ui.spacing_mut().item_spacing.y = METER_GAP;
                            theme::draw_vu_meter(ui, master.meter_l, METER_W, 120.0);
                            theme::draw_vu_meter(ui, master.meter_r, METER_W, 120.0);
                        });
                    });
                });
            });
        });
    });
}

// ── helper widgets ────────────────────────────────────────────────────────────

/// dB scale ticks to the left of the fader.
fn draw_db_scale(ui: &mut Ui, height: f32, color: Color32) {
    let width = 20.0;
    let (rect, _) = ui.allocate_exact_size(Vec2::new(width, height), Sense::hover());

    let font = FontId::new(7.5, FontFamily::Monospace);

    for &db in DB_MARKS {
        let linear = db_to_linear(db).min(1.0);
        let y = rect.min.y + (1.0 - linear) * height;
        // Tick line
        ui.painter().line_segment(
            [
                Pos2::new(rect.max.x - 4.0, y),
                Pos2::new(rect.max.x, y),
            ],
            Stroke::new(1.0, color),
        );
        // Label
        let label = if db == 0.0 { "0".to_string() } else { format!("{}", db as i32) };
        ui.painter().text(
            Pos2::new(rect.max.x - 6.0, y),
            Align2::RIGHT_CENTER,
            label,
            font.clone(),
            color,
        );
    }
}

/// Static (non-interactive) fader indicator — used for master strip.
fn draw_static_fader(ui: &mut Ui, pos: f32, width: f32, height: f32) {
    let (rect, _) = ui.allocate_exact_size(Vec2::new(width, height), Sense::hover());
    let rail_x = rect.center().x;

    // Rail
    ui.painter().rect_filled(
        Rect::from_center_size(
            Pos2::new(rail_x, rect.center().y),
            Vec2::new(3.0, height),
        ),
        1.0,
        Color32::from_rgba_unmultiplied(0xFF, 0xFF, 0xFF, 15),
    );

    // Thumb (just a horizontal line)
    let thumb_y = rect.min.y + pos * height;
    ui.painter().line_segment(
        [
            Pos2::new(rect.min.x + 1.0, thumb_y),
            Pos2::new(rect.max.x - 1.0, thumb_y),
        ],
        Stroke::new(2.0, theme::ACCENT),
    );
}

fn section_header(ui: &mut Ui, label: &str) {
    ui.horizontal(|ui| {
        ui.label(
            RichText::new(label)
                .size(9.0)
                .color(theme::FAINT)
                .strong(),
        );
    });
}

fn placeholder_slot(ui: &mut Ui, color: Color32) {
    let (rect, _) = ui.allocate_exact_size(Vec2::new(60.0, 18.0), Sense::hover());
    ui.painter().rect_filled(rect, 2.0, color);
}

fn cmd(command_id: &str, payload: serde_json::Value) -> OutgoingMessage {
    OutgoingMessage::Command {
        command_id: command_id.to_string(),
        payload,
    }
}
