# GitHub Sponsors
github: arizkami

# Patreon
# patreon: arizkami

# Open Collective
# open_collective: futureboard

# Ko-fi
# ko_fi: arizkami

# Tidelift
# tidelift: npm/babel

# Community Bridge
# community_bridge: futureboard

# Liberapay
# liberapay: arizkami

# IssueHunt
# issuehunt: arizkami

# Otechie
# otechie: arizkami

# LFX Mentorship
# lfx_crowdfunding: futureboard

# Custom funding links
custom:
  - https://futureboard.studio
