//! What the Accent Analyzer reads: score facts, and nothing else.
//!
//! This is the runtime half of `neural/accent/features.py`. The two must agree
//! feature for feature and value for value — a model fed a differently-computed
//! vector is being asked a question it was never trained on — so the order of
//! [`ACCENT_INPUT_FEATURES`] is a contract, and `accent::parity` checks a
//! fixture generated by the training side against this code.
//!
//! Two things are deliberately absent.
//!
//! **Velocity.** URMP's score MIDI carries real dynamic markings, so a model
//! given that column could learn "accent is velocity" and score respectably
//! doing it. Leaving it out makes "the same velocity can produce different
//! accents" structural rather than aspirational: the analyser cannot copy a
//! number it never sees.
//!
//! **Articulation.** URMP has no articulation annotation, so the column would
//! be constant through training and pure extrapolation here. Articulation
//! enters downstream instead, where an accent of a given strength is *realised*
//! differently on a pizzicato than on a sustain.

use crate::components::timeline::timeline_state::MidiNoteState;

use super::meter::Meter;

/// Order is the contract between training, export, and this runtime.
/// Append only; never reorder, never reuse a slot.
pub const ACCENT_INPUT_FEATURES: [&str; 33] = [
    // meter
    "metrical_strength",
    "is_downbeat",
    "bar_progress_sin",
    "bar_progress_cos",
    "beat_offset",
    "syncopation",
    "spans_stronger_beat",
    "meter_beats_norm",
    "meter_is_compound",
    "meter_is_irregular",
    // duration
    "log_duration_beats",
    "duration_vs_local",
    "long_after_short",
    // separation
    "rest_before",
    "rest_after",
    "starts_after_rest",
    // melody
    "previous_interval",
    "next_interval",
    "leap_into",
    "is_local_peak",
    "is_local_trough",
    "pitch_vs_local",
    "contour_turn",
    "repeated_note",
    "is_phrase_peak",
    "is_window_peak",
    "is_window_trough",
    // phrase
    "phrase_progress",
    "is_phrase_start",
    "is_phrase_end",
    "log_phrase_length",
    // global
    "pitch_norm",
    "log_tempo",
];

pub const ACCENT_INPUT_SIZE: usize = ACCENT_INPUT_FEATURES.len();

/// A written rest at least this long, in quarter-note beats, starts a new
/// group. See the training module for why a sixteenth: URMP's scores notate a
/// line with each note-off on the next note-on, so 95% of written gaps are
/// under 0.027 beats and the distribution then jumps to 0.5, leaving a
/// sixteenth in the empty part of it.
pub const PHRASE_GAP_BEATS: f32 = 0.25;

/// A note at least this many times the local median duration ends its group.
///
/// The other half of the segmentation, and on the training corpus the half that
/// does the work: cutting at rests alone left groups averaging 119 notes, which
/// makes "where am I in the phrase" mean "where am I in the piece".
pub const PHRASE_ARRIVAL_RATIO: f32 = 2.0;

/// Notes either side used for the "compared with its neighbours" features.
pub const LOCAL_WINDOW_NOTES: usize = 6;

/// One note of a phrase, as the analyser sees it.
///
/// Built from clip state by [`contexts_from_notes`]. Deliberately not
/// `MidiNoteState`: the analyser needs derived context (group membership, the
/// group's highest pitch) that a note does not carry, and computing it once per
/// phrase rather than once per feature keeps the whole pass linear.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct NoteContext {
    pub pitch: u8,
    /// Quarter-note beats from the start of the piece.
    pub onset_beats: f32,
    pub duration_beats: f32,
    /// Beats of rest before this note. `None` at the start of the phrase.
    pub rest_before_beats: Option<f32>,
    pub rest_after_beats: Option<f32>,
    pub phrase_position: usize,
    pub phrase_length: usize,
    pub phrase_peak_pitch: u8,
    pub tempo_bpm: f32,
}

fn clamp(value: f32, low: f32, high: f32) -> f32 {
    if value.is_finite() {
        value.clamp(low, high)
    } else {
        0.0
    }
}

fn median(values: &mut Vec<f32>) -> f32 {
    if values.is_empty() {
        return 0.0;
    }
    values.sort_by(f32::total_cmp);
    let middle = values.len() / 2;
    if values.len() % 2 == 0 {
        (values[middle - 1] + values[middle]) * 0.5
    } else {
        values[middle]
    }
}

/// Median of a window around `index`, excluding the value at `index` itself.
fn local_median(values: &[f32], index: usize, window: usize) -> f32 {
    let low = index.saturating_sub(window);
    let high = (index + window + 1).min(values.len());
    let mut neighbours: Vec<f32> = (low..high)
        .filter(|other| *other != index)
        .map(|other| values[other])
        .collect();
    if neighbours.is_empty() {
        return values[index];
    }
    median(&mut neighbours)
}

/// Build one context per note, with groups cut at rests and after long notes.
///
/// `notes` must be sorted by start. `clip_start_beat` places the clip on the
/// project timeline: metrical strength is measured against the project's bars,
/// so a clip that begins on beat 3 of a bar must analyse as beginning there.
pub fn contexts_from_notes(
    notes: &[MidiNoteState],
    clip_start_beat: f32,
    tempo_bpm: f32,
) -> Vec<NoteContext> {
    if notes.is_empty() {
        return Vec::new();
    }
    let count = notes.len();
    let onsets: Vec<f32> = notes
        .iter()
        .map(|note| clip_start_beat + note.start)
        .collect();
    let durations: Vec<f32> = notes.iter().map(|note| note.duration.max(1e-4)).collect();

    let mut rests_before: Vec<Option<f32>> = Vec::with_capacity(count);
    rests_before.push(None);
    for index in 1..count {
        let previous_end = onsets[index - 1] + durations[index - 1];
        rests_before.push(Some((onsets[index] - previous_end).max(0.0)));
    }
    let mut rests_after: Vec<Option<f32>> = Vec::with_capacity(count);
    for index in 0..count {
        rests_after.push(if index + 1 >= count {
            None
        } else {
            Some((onsets[index + 1] - (onsets[index] + durations[index])).max(0.0))
        });
    }

    let mut phrase_of: Vec<usize> = Vec::with_capacity(count);
    let mut phrase = 0usize;
    for index in 0..count {
        let mut boundary = rests_before[index].is_some_and(|gap| gap > PHRASE_GAP_BEATS);
        if !boundary && index > 0 {
            let previous = index - 1;
            let low = previous.saturating_sub(LOCAL_WINDOW_NOTES);
            let high = (index + LOCAL_WINDOW_NOTES).min(count);
            let mut neighbours: Vec<f32> = (low..high)
                .filter(|other| *other != previous)
                .map(|other| durations[other])
                .collect();
            if !neighbours.is_empty() {
                boundary = durations[previous] >= PHRASE_ARRIVAL_RATIO * median(&mut neighbours);
            }
        }
        if boundary {
            phrase += 1;
        }
        phrase_of.push(phrase);
    }

    let groups = phrase + 1;
    let mut lengths = vec![0usize; groups];
    let mut peaks = vec![0u8; groups];
    for (index, &current) in phrase_of.iter().enumerate() {
        lengths[current] += 1;
        peaks[current] = peaks[current].max(notes[index].pitch);
    }
    let mut positions = vec![0usize; groups];

    (0..count)
        .map(|index| {
            let current = phrase_of[index];
            let position = positions[current];
            positions[current] += 1;
            NoteContext {
                pitch: notes[index].pitch,
                onset_beats: onsets[index],
                duration_beats: durations[index],
                rest_before_beats: rests_before[index],
                rest_after_beats: rests_after[index],
                phrase_position: position,
                phrase_length: lengths[current],
                phrase_peak_pitch: peaks[current],
                tempo_bpm,
            }
        })
        .collect()
}

/// The score-side description of one note, in [`ACCENT_INPUT_FEATURES`] order.
pub fn note_feature_vector(
    notes: &[NoteContext],
    index: usize,
    meter: &Meter,
    durations: &[f32],
    pitches: &[f32],
) -> [f32; ACCENT_INPUT_SIZE] {
    let note = notes[index];
    let previous = index.checked_sub(1).map(|position| notes[position]);
    let following = notes.get(index + 1).copied();

    let strength = meter.beat_strength(note.onset_beats);
    let displaced = meter.syncopation(note.onset_beats, note.duration_beats);

    let bar = meter.bar_beats.max(1e-6);
    let bar_position = note.onset_beats.rem_euclid(bar) / bar;
    let phase = std::f32::consts::TAU * bar_position;

    // Distance to the nearest beat, as a fraction of the local beat. Zero on a
    // beat, 0.5 exactly between two, and it says something metrical strength
    // does not: a note a sixteenth late of beat 3 and one exactly on the
    // offbeat both score 0.25 for strength but are different gestures.
    let within = note.onset_beats.rem_euclid(bar);
    let mut starts = meter.beat_starts();
    starts.push(bar);
    let nearest = starts
        .iter()
        .copied()
        .min_by(|a, b| (within - a).abs().total_cmp(&(within - b).abs()))
        .unwrap_or(0.0);
    let beat_length = (meter.groups[0] as f32 * meter.unit_beats).max(1e-6);
    let beat_offset = clamp((within - nearest).abs() / beat_length, 0.0, 1.0);

    let local_duration = local_median(durations, index, LOCAL_WINDOW_NOTES);
    let duration_vs_local = clamp(
        (note.duration_beats.max(1e-4) / local_duration.max(1e-4)).log2(),
        -3.0,
        3.0,
    ) / 3.0;
    let long_after_short = previous
        .is_some_and(|previous| note.duration_beats >= 1.5 * previous.duration_beats.max(1e-6));

    let rest_before = note.rest_before_beats.unwrap_or(0.0);
    let rest_after = note.rest_after_beats.unwrap_or(0.0);

    let previous_interval = previous.map_or(0.0, |p| note.pitch as f32 - p.pitch as f32);
    let next_interval = following.map_or(0.0, |f| f.pitch as f32 - note.pitch as f32);
    let peak = previous
        .zip(following)
        .is_some_and(|(previous, following)| {
            note.pitch > previous.pitch && note.pitch > following.pitch
        });
    let trough = previous
        .zip(following)
        .is_some_and(|(previous, following)| {
            note.pitch < previous.pitch && note.pitch < following.pitch
        });
    let contour_turn = previous.zip(following).is_some_and(|_| {
        previous_interval != 0.0
            && next_interval != 0.0
            && previous_interval.is_sign_negative() != next_interval.is_sign_negative()
    });

    let local_pitch = local_median(pitches, index, LOCAL_WINDOW_NOTES);
    let pitch_vs_local = clamp((note.pitch as f32 - local_pitch) / 12.0, -2.0, 2.0);

    let low = index.saturating_sub(LOCAL_WINDOW_NOTES);
    let high = (index + LOCAL_WINDOW_NOTES + 1).min(notes.len());
    let mut window_high = None::<u8>;
    let mut window_low = None::<u8>;
    for other in low..high {
        if other == index {
            continue;
        }
        let pitch = notes[other].pitch;
        window_high = Some(window_high.map_or(pitch, |current: u8| current.max(pitch)));
        window_low = Some(window_low.map_or(pitch, |current: u8| current.min(pitch)));
    }

    let mut out = [0.0_f32; ACCENT_INPUT_SIZE];
    out[0] = strength;
    out[1] = if strength >= 0.999 { 1.0 } else { 0.0 };
    out[2] = phase.sin();
    out[3] = phase.cos();
    out[4] = beat_offset;
    out[5] = clamp(displaced, 0.0, 1.0);
    out[6] = if displaced > 1e-6 { 1.0 } else { 0.0 };
    out[7] = clamp(meter.beat_count() as f32 / 6.0, 0.0, 2.0);
    out[8] = if meter.is_compound() { 1.0 } else { 0.0 };
    out[9] = if meter.is_irregular() { 1.0 } else { 0.0 };
    out[10] = clamp(note.duration_beats.max(1e-3).log2(), -6.0, 4.0) / 4.0;
    out[11] = duration_vs_local;
    out[12] = if long_after_short { 1.0 } else { 0.0 };
    out[13] = clamp(rest_before.max(0.0).ln_1p(), 0.0, 3.0) / 3.0;
    out[14] = clamp(rest_after.max(0.0).ln_1p(), 0.0, 3.0) / 3.0;
    out[15] = if rest_before >= 0.25 { 1.0 } else { 0.0 };
    out[16] = clamp(previous_interval / 12.0, -2.0, 2.0);
    out[17] = clamp(next_interval / 12.0, -2.0, 2.0);
    out[18] = clamp(previous_interval.abs() / 12.0, 0.0, 2.0);
    out[19] = if peak { 1.0 } else { 0.0 };
    out[20] = if trough { 1.0 } else { 0.0 };
    out[21] = pitch_vs_local;
    out[22] = if contour_turn { 1.0 } else { 0.0 };
    out[23] = if previous.is_some() && previous_interval == 0.0 {
        1.0
    } else {
        0.0
    };
    out[24] = if note.pitch >= note.phrase_peak_pitch {
        1.0
    } else {
        0.0
    };
    out[25] = if window_high.is_some_and(|high| note.pitch > high) {
        1.0
    } else {
        0.0
    };
    out[26] = if window_low.is_some_and(|low| note.pitch < low) {
        1.0
    } else {
        0.0
    };
    out[27] = note.phrase_position as f32 / note.phrase_length.saturating_sub(1).max(1) as f32;
    out[28] = if note.phrase_position == 0 { 1.0 } else { 0.0 };
    out[29] = if note.phrase_position + 1 == note.phrase_length {
        1.0
    } else {
        0.0
    };
    out[30] = clamp((note.phrase_length.max(1) as f32).log2(), 0.0, 10.0) / 10.0;
    out[31] = (note.pitch as f32 - 69.0) / 24.0;
    out[32] = clamp((note.tempo_bpm.max(1e-6) / 120.0).log2(), -2.0, 2.0);
    out
}

/// `(notes * ACCENT_INPUT_SIZE)` row-major, in score order.
pub fn phrase_feature_matrix(notes: &[NoteContext], meter: &Meter) -> Vec<f32> {
    let durations: Vec<f32> = notes.iter().map(|note| note.duration_beats).collect();
    let pitches: Vec<f32> = notes.iter().map(|note| note.pitch as f32).collect();
    let mut out = Vec::with_capacity(notes.len() * ACCENT_INPUT_SIZE);
    for index in 0..notes.len() {
        out.extend_from_slice(&note_feature_vector(
            notes, index, meter, &durations, &pitches,
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn note(pitch: u8, start: f32, duration: f32) -> MidiNoteState {
        MidiNoteState::new(pitch, start, duration, 96)
    }

    fn index_of(name: &str) -> usize {
        ACCENT_INPUT_FEATURES
            .iter()
            .position(|feature| *feature == name)
            .expect("feature exists")
    }

    #[test]
    fn the_feature_order_has_no_duplicates() {
        let mut names = ACCENT_INPUT_FEATURES.to_vec();
        names.sort_unstable();
        let count = names.len();
        names.dedup();
        assert_eq!(names.len(), count, "a feature slot is used twice");
    }

    /// The structural guarantee behind "the same velocity can still produce
    /// different accents": the analyser is never given velocity at all.
    #[test]
    fn no_feature_reads_velocity_or_articulation() {
        for name in ACCENT_INPUT_FEATURES {
            assert!(
                !name.contains("velocity") && !name.contains("articulation"),
                "{name} would let the analyser copy the value it is meant to \
                 be independent of"
            );
        }
    }

    #[test]
    fn a_written_rest_starts_a_new_group() {
        let notes = [
            note(60, 0.0, 1.0),
            note(62, 1.0, 1.0),
            // A beat of rest.
            note(64, 3.0, 1.0),
        ];
        let contexts = contexts_from_notes(&notes, 0.0, 120.0);
        assert_eq!(contexts[0].phrase_position, 0);
        assert_eq!(contexts[1].phrase_position, 1);
        assert_eq!(
            contexts[2].phrase_position, 0,
            "the note after the rest opens a group"
        );
        assert_eq!(contexts[2].phrase_length, 1);
    }

    #[test]
    fn a_long_note_ends_its_group_even_without_a_rest() {
        let mut notes: Vec<MidiNoteState> = (0..6)
            .map(|index| note(60 + index as u8, index as f32 * 0.5, 0.5))
            .collect();
        // A note four times the length of its neighbours, then more eighths.
        notes.push(note(72, 3.0, 2.0));
        notes.extend((0..6).map(|index| note(60 + index as u8, 5.0 + index as f32 * 0.5, 0.5)));
        let contexts = contexts_from_notes(&notes, 0.0, 120.0);
        assert_eq!(
            contexts[7].phrase_position, 0,
            "the note after the arrival opens a group"
        );
    }

    /// A clip dropped at beat 3 of a bar must analyse as starting there, or
    /// every accent in it is a bar's worth of meter out.
    #[test]
    fn the_clip_position_moves_the_metrical_reading() {
        let notes = [note(60, 0.0, 1.0)];
        let meter = Meter::from_signature(4, 4);
        let strength = index_of("metrical_strength");

        let at_bar_line = contexts_from_notes(&notes, 0.0, 120.0);
        let at_beat_two = contexts_from_notes(&notes, 1.0, 120.0);
        let durations = [1.0_f32];
        let pitches = [60.0_f32];
        assert_eq!(
            note_feature_vector(&at_bar_line, 0, &meter, &durations, &pitches)[strength],
            1.0
        );
        assert_eq!(
            note_feature_vector(&at_beat_two, 0, &meter, &durations, &pitches)[strength],
            0.5
        );
    }

    #[test]
    fn a_melodic_peak_is_marked_as_one() {
        let notes = [
            note(60, 0.0, 0.5),
            note(62, 0.5, 0.5),
            note(64, 1.0, 0.5),
            note(79, 1.5, 0.5),
            note(65, 2.0, 0.5),
        ];
        let contexts = contexts_from_notes(&notes, 0.0, 120.0);
        let meter = Meter::from_signature(4, 4);
        let durations: Vec<f32> = contexts.iter().map(|c| c.duration_beats).collect();
        let pitches: Vec<f32> = contexts.iter().map(|c| c.pitch as f32).collect();
        let vector = note_feature_vector(&contexts, 3, &meter, &durations, &pitches);
        assert_eq!(vector[index_of("is_local_peak")], 1.0);
        assert_eq!(vector[index_of("is_window_peak")], 1.0);
        assert!(vector[index_of("pitch_vs_local")] > 0.5);
        // And a passing note in the middle of the run is not.
        let passing = note_feature_vector(&contexts, 1, &meter, &durations, &pitches);
        assert_eq!(passing[index_of("is_local_peak")], 0.0);
        assert_eq!(passing[index_of("is_window_peak")], 0.0);
    }

    #[test]
    fn every_feature_of_a_degenerate_phrase_is_finite() {
        // One note, zero-ish duration, absurd tempo: nothing here may produce a
        // NaN, because one NaN input poisons the whole GRU pass.
        let notes = [note(0, 0.0, 1e-6)];
        let contexts = contexts_from_notes(&notes, 0.0, 1e-6);
        let meter = Meter::from_signature(4, 4);
        let vector = note_feature_vector(&contexts, 0, &meter, &[1e-6], &[0.0]);
        for (index, value) in vector.iter().enumerate() {
            assert!(
                value.is_finite(),
                "{} is {value}",
                ACCENT_INPUT_FEATURES[index]
            );
        }
    }
}
