// DO NOT EDIT: generated by ara2-bridge xtask 0.3.0.
// Source repository: https://github.com/Celemony/ARA_API
// Source tag: releases/2.3.0
// Normative ARA API commit: 65ec5c43b943a48cb5446f448a0492db6af8534b
// Generator: ara2-bridge xtask 0.3.0
// SPDX-License-Identifier: Apache-2.0

//! Generated host-to-plug-in document-controller call shells.

#![allow(
    dead_code,
    non_snake_case,
    unsafe_op_in_unsafe_fn,
    clippy::undocumented_unsafe_blocks
)]

use ara2_bridge_core::AraError;
use ara2_bridge_sys::*;

/// Exact generated description of one controller callback.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct DispatchMethod {
    /// Released C callback name.
    pub c_name: &'static str,
    /// Zero-based slot in released header order.
    pub index: usize,
    /// Byte offset of the callback field.
    pub field_offset: usize,
    /// Minimum represented interface size for this slot.
    pub field_extent: usize,
}

/// All controller callbacks in released header order.
pub static DISPATCH_METHODS: &[DispatchMethod] = &[
    DispatchMethod { c_name: "destroyDocumentController", index: 0, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, destroyDocumentController), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_DESTROY_DOCUMENT_CONTROLLER },
    DispatchMethod { c_name: "getFactory", index: 1, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, getFactory), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_FACTORY },
    DispatchMethod { c_name: "beginEditing", index: 2, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, beginEditing), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_BEGIN_EDITING },
    DispatchMethod { c_name: "endEditing", index: 3, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, endEditing), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_END_EDITING },
    DispatchMethod { c_name: "notifyModelUpdates", index: 4, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, notifyModelUpdates), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_NOTIFY_MODEL_UPDATES },
    DispatchMethod { c_name: "beginRestoringDocumentFromArchive", index: 5, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, beginRestoringDocumentFromArchive), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_BEGIN_RESTORING_DOCUMENT_FROM_ARCHIVE },
    DispatchMethod { c_name: "endRestoringDocumentFromArchive", index: 6, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, endRestoringDocumentFromArchive), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_END_RESTORING_DOCUMENT_FROM_ARCHIVE },
    DispatchMethod { c_name: "storeDocumentToArchive", index: 7, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, storeDocumentToArchive), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_STORE_DOCUMENT_TO_ARCHIVE },
    DispatchMethod { c_name: "updateDocumentProperties", index: 8, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, updateDocumentProperties), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_UPDATE_DOCUMENT_PROPERTIES },
    DispatchMethod { c_name: "createMusicalContext", index: 9, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, createMusicalContext), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_CREATE_MUSICAL_CONTEXT },
    DispatchMethod { c_name: "updateMusicalContextProperties", index: 10, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, updateMusicalContextProperties), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_UPDATE_MUSICAL_CONTEXT_PROPERTIES },
    DispatchMethod { c_name: "updateMusicalContextContent", index: 11, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, updateMusicalContextContent), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_UPDATE_MUSICAL_CONTEXT_CONTENT },
    DispatchMethod { c_name: "destroyMusicalContext", index: 12, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, destroyMusicalContext), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_DESTROY_MUSICAL_CONTEXT },
    DispatchMethod { c_name: "createAudioSource", index: 13, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, createAudioSource), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_CREATE_AUDIO_SOURCE },
    DispatchMethod { c_name: "updateAudioSourceProperties", index: 14, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, updateAudioSourceProperties), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_UPDATE_AUDIO_SOURCE_PROPERTIES },
    DispatchMethod { c_name: "updateAudioSourceContent", index: 15, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, updateAudioSourceContent), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_UPDATE_AUDIO_SOURCE_CONTENT },
    DispatchMethod { c_name: "enableAudioSourceSamplesAccess", index: 16, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, enableAudioSourceSamplesAccess), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_ENABLE_AUDIO_SOURCE_SAMPLES_ACCESS },
    DispatchMethod { c_name: "deactivateAudioSourceForUndoHistory", index: 17, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, deactivateAudioSourceForUndoHistory), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_DEACTIVATE_AUDIO_SOURCE_FOR_UNDO_HISTORY },
    DispatchMethod { c_name: "destroyAudioSource", index: 18, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, destroyAudioSource), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_DESTROY_AUDIO_SOURCE },
    DispatchMethod { c_name: "createAudioModification", index: 19, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, createAudioModification), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_CREATE_AUDIO_MODIFICATION },
    DispatchMethod { c_name: "cloneAudioModification", index: 20, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, cloneAudioModification), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_CLONE_AUDIO_MODIFICATION },
    DispatchMethod { c_name: "updateAudioModificationProperties", index: 21, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, updateAudioModificationProperties), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_UPDATE_AUDIO_MODIFICATION_PROPERTIES },
    DispatchMethod { c_name: "deactivateAudioModificationForUndoHistory", index: 22, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, deactivateAudioModificationForUndoHistory), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_DEACTIVATE_AUDIO_MODIFICATION_FOR_UNDO_HISTORY },
    DispatchMethod { c_name: "destroyAudioModification", index: 23, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, destroyAudioModification), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_DESTROY_AUDIO_MODIFICATION },
    DispatchMethod { c_name: "createPlaybackRegion", index: 24, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, createPlaybackRegion), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_CREATE_PLAYBACK_REGION },
    DispatchMethod { c_name: "updatePlaybackRegionProperties", index: 25, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, updatePlaybackRegionProperties), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_UPDATE_PLAYBACK_REGION_PROPERTIES },
    DispatchMethod { c_name: "destroyPlaybackRegion", index: 26, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, destroyPlaybackRegion), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_DESTROY_PLAYBACK_REGION },
    DispatchMethod { c_name: "isAudioSourceContentAvailable", index: 27, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, isAudioSourceContentAvailable), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_IS_AUDIO_SOURCE_CONTENT_AVAILABLE },
    DispatchMethod { c_name: "isAudioSourceContentAnalysisIncomplete", index: 28, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, isAudioSourceContentAnalysisIncomplete), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_IS_AUDIO_SOURCE_CONTENT_ANALYSIS_INCOMPLETE },
    DispatchMethod { c_name: "requestAudioSourceContentAnalysis", index: 29, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, requestAudioSourceContentAnalysis), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_REQUEST_AUDIO_SOURCE_CONTENT_ANALYSIS },
    DispatchMethod { c_name: "getAudioSourceContentGrade", index: 30, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, getAudioSourceContentGrade), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_AUDIO_SOURCE_CONTENT_GRADE },
    DispatchMethod { c_name: "createAudioSourceContentReader", index: 31, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, createAudioSourceContentReader), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_CREATE_AUDIO_SOURCE_CONTENT_READER },
    DispatchMethod { c_name: "isAudioModificationContentAvailable", index: 32, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, isAudioModificationContentAvailable), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_IS_AUDIO_MODIFICATION_CONTENT_AVAILABLE },
    DispatchMethod { c_name: "getAudioModificationContentGrade", index: 33, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, getAudioModificationContentGrade), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_AUDIO_MODIFICATION_CONTENT_GRADE },
    DispatchMethod { c_name: "createAudioModificationContentReader", index: 34, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, createAudioModificationContentReader), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_CREATE_AUDIO_MODIFICATION_CONTENT_READER },
    DispatchMethod { c_name: "isPlaybackRegionContentAvailable", index: 35, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, isPlaybackRegionContentAvailable), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_IS_PLAYBACK_REGION_CONTENT_AVAILABLE },
    DispatchMethod { c_name: "getPlaybackRegionContentGrade", index: 36, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, getPlaybackRegionContentGrade), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_PLAYBACK_REGION_CONTENT_GRADE },
    DispatchMethod { c_name: "createPlaybackRegionContentReader", index: 37, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, createPlaybackRegionContentReader), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_CREATE_PLAYBACK_REGION_CONTENT_READER },
    DispatchMethod { c_name: "getContentReaderEventCount", index: 38, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, getContentReaderEventCount), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_CONTENT_READER_EVENT_COUNT },
    DispatchMethod { c_name: "getContentReaderDataForEvent", index: 39, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, getContentReaderDataForEvent), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_CONTENT_READER_DATA_FOR_EVENT },
    DispatchMethod { c_name: "destroyContentReader", index: 40, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, destroyContentReader), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_DESTROY_CONTENT_READER },
    DispatchMethod { c_name: "createRegionSequence", index: 41, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, createRegionSequence), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_CREATE_REGION_SEQUENCE },
    DispatchMethod { c_name: "updateRegionSequenceProperties", index: 42, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, updateRegionSequenceProperties), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_UPDATE_REGION_SEQUENCE_PROPERTIES },
    DispatchMethod { c_name: "destroyRegionSequence", index: 43, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, destroyRegionSequence), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_DESTROY_REGION_SEQUENCE },
    DispatchMethod { c_name: "getPlaybackRegionHeadAndTailTime", index: 44, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, getPlaybackRegionHeadAndTailTime), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_PLAYBACK_REGION_HEAD_AND_TAIL_TIME },
    DispatchMethod { c_name: "restoreObjectsFromArchive", index: 45, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, restoreObjectsFromArchive), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_RESTORE_OBJECTS_FROM_ARCHIVE },
    DispatchMethod { c_name: "storeObjectsToArchive", index: 46, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, storeObjectsToArchive), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_STORE_OBJECTS_TO_ARCHIVE },
    DispatchMethod { c_name: "getProcessingAlgorithmsCount", index: 47, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, getProcessingAlgorithmsCount), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_PROCESSING_ALGORITHMS_COUNT },
    DispatchMethod { c_name: "getProcessingAlgorithmProperties", index: 48, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, getProcessingAlgorithmProperties), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_PROCESSING_ALGORITHM_PROPERTIES },
    DispatchMethod { c_name: "getProcessingAlgorithmForAudioSource", index: 49, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, getProcessingAlgorithmForAudioSource), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_PROCESSING_ALGORITHM_FOR_AUDIO_SOURCE },
    DispatchMethod { c_name: "requestProcessingAlgorithmForAudioSource", index: 50, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, requestProcessingAlgorithmForAudioSource), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_REQUEST_PROCESSING_ALGORITHM_FOR_AUDIO_SOURCE },
    DispatchMethod { c_name: "isLicensedForCapabilities", index: 51, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, isLicensedForCapabilities), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_IS_LICENSED_FOR_CAPABILITIES },
    DispatchMethod { c_name: "storeAudioSourceToAudioFileChunk", index: 52, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, storeAudioSourceToAudioFileChunk), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_STORE_AUDIO_SOURCE_TO_AUDIO_FILE_CHUNK },
    DispatchMethod { c_name: "isAudioModificationPreservingAudioSourceSignal", index: 53, field_offset: ::std::mem::offset_of!(ARADocumentControllerInterface, isAudioModificationPreservingAudioSourceSignal), field_extent: layout::ARADOCUMENT_CONTROLLER_INTERFACE_IS_AUDIO_MODIFICATION_PRESERVING_AUDIO_SOURCE_SIGNAL },
];

pub(crate) unsafe fn destroy_document_controller(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<unsafe extern "C" fn(controllerRef: ARADocumentControllerRef)>(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_DESTROY_DOCUMENT_CONTROLLER,
            ::std::mem::offset_of!(ARADocumentControllerInterface, destroyDocumentController),
            "destroyDocumentController",
        )?
    };
    unsafe { callback(controllerRef) };
    Ok(())
}

pub(crate) unsafe fn get_factory(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
) -> Result<*const ARAFactory, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(controllerRef: ARADocumentControllerRef) -> *const ARAFactory,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_FACTORY,
            ::std::mem::offset_of!(ARADocumentControllerInterface, getFactory),
            "getFactory",
        )?
    };
    Ok(unsafe { callback(controllerRef) })
}

pub(crate) unsafe fn begin_editing(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<unsafe extern "C" fn(controllerRef: ARADocumentControllerRef)>(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_BEGIN_EDITING,
            ::std::mem::offset_of!(ARADocumentControllerInterface, beginEditing),
            "beginEditing",
        )?
    };
    unsafe { callback(controllerRef) };
    Ok(())
}

pub(crate) unsafe fn end_editing(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<unsafe extern "C" fn(controllerRef: ARADocumentControllerRef)>(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_END_EDITING,
            ::std::mem::offset_of!(ARADocumentControllerInterface, endEditing),
            "endEditing",
        )?
    };
    unsafe { callback(controllerRef) };
    Ok(())
}

pub(crate) unsafe fn notify_model_updates(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<unsafe extern "C" fn(controllerRef: ARADocumentControllerRef)>(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_NOTIFY_MODEL_UPDATES,
            ::std::mem::offset_of!(ARADocumentControllerInterface, notifyModelUpdates),
            "notifyModelUpdates",
        )?
    };
    unsafe { callback(controllerRef) };
    Ok(())
}

pub(crate) unsafe fn begin_restoring_document_from_archive(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    archiveReaderHostRef: ARAArchiveReaderHostRef,
) -> Result<ARABool, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                archiveReaderHostRef: ARAArchiveReaderHostRef,
            ) -> ARABool,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_BEGIN_RESTORING_DOCUMENT_FROM_ARCHIVE,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                beginRestoringDocumentFromArchive
            ),
            "beginRestoringDocumentFromArchive",
        )?
    };
    Ok(unsafe { callback(controllerRef, archiveReaderHostRef) })
}

pub(crate) unsafe fn end_restoring_document_from_archive(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    archiveReaderHostRef: ARAArchiveReaderHostRef,
) -> Result<ARABool, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                archiveReaderHostRef: ARAArchiveReaderHostRef,
            ) -> ARABool,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_END_RESTORING_DOCUMENT_FROM_ARCHIVE,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                endRestoringDocumentFromArchive
            ),
            "endRestoringDocumentFromArchive",
        )?
    };
    Ok(unsafe { callback(controllerRef, archiveReaderHostRef) })
}

pub(crate) unsafe fn store_document_to_archive(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    archiveWriterHostRef: ARAArchiveWriterHostRef,
) -> Result<ARABool, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                archiveWriterHostRef: ARAArchiveWriterHostRef,
            ) -> ARABool,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_STORE_DOCUMENT_TO_ARCHIVE,
            ::std::mem::offset_of!(ARADocumentControllerInterface, storeDocumentToArchive),
            "storeDocumentToArchive",
        )?
    };
    Ok(unsafe { callback(controllerRef, archiveWriterHostRef) })
}

pub(crate) unsafe fn update_document_properties(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    properties: *const ARADocumentProperties,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                properties: *const ARADocumentProperties,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_UPDATE_DOCUMENT_PROPERTIES,
            ::std::mem::offset_of!(ARADocumentControllerInterface, updateDocumentProperties),
            "updateDocumentProperties",
        )?
    };
    unsafe { callback(controllerRef, properties) };
    Ok(())
}

pub(crate) unsafe fn create_musical_context(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    hostRef: ARAMusicalContextHostRef,
    properties: *const ARAMusicalContextProperties,
) -> Result<ARAMusicalContextRef, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                hostRef: ARAMusicalContextHostRef,
                properties: *const ARAMusicalContextProperties,
            ) -> ARAMusicalContextRef,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_CREATE_MUSICAL_CONTEXT,
            ::std::mem::offset_of!(ARADocumentControllerInterface, createMusicalContext),
            "createMusicalContext",
        )?
    };
    Ok(unsafe { callback(controllerRef, hostRef, properties) })
}

pub(crate) unsafe fn update_musical_context_properties(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    musicalContextRef: ARAMusicalContextRef,
    properties: *const ARAMusicalContextProperties,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                musicalContextRef: ARAMusicalContextRef,
                properties: *const ARAMusicalContextProperties,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_UPDATE_MUSICAL_CONTEXT_PROPERTIES,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                updateMusicalContextProperties
            ),
            "updateMusicalContextProperties",
        )?
    };
    unsafe { callback(controllerRef, musicalContextRef, properties) };
    Ok(())
}

pub(crate) unsafe fn update_musical_context_content(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    musicalContextRef: ARAMusicalContextRef,
    range: *const ARAContentTimeRange,
    flags: ARAContentUpdateFlags,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                musicalContextRef: ARAMusicalContextRef,
                range: *const ARAContentTimeRange,
                flags: ARAContentUpdateFlags,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_UPDATE_MUSICAL_CONTEXT_CONTENT,
            ::std::mem::offset_of!(ARADocumentControllerInterface, updateMusicalContextContent),
            "updateMusicalContextContent",
        )?
    };
    unsafe { callback(controllerRef, musicalContextRef, range, flags) };
    Ok(())
}

pub(crate) unsafe fn destroy_musical_context(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    musicalContextRef: ARAMusicalContextRef,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                musicalContextRef: ARAMusicalContextRef,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_DESTROY_MUSICAL_CONTEXT,
            ::std::mem::offset_of!(ARADocumentControllerInterface, destroyMusicalContext),
            "destroyMusicalContext",
        )?
    };
    unsafe { callback(controllerRef, musicalContextRef) };
    Ok(())
}

pub(crate) unsafe fn create_audio_source(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    hostRef: ARAAudioSourceHostRef,
    properties: *const ARAAudioSourceProperties,
) -> Result<ARAAudioSourceRef, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                hostRef: ARAAudioSourceHostRef,
                properties: *const ARAAudioSourceProperties,
            ) -> ARAAudioSourceRef,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_CREATE_AUDIO_SOURCE,
            ::std::mem::offset_of!(ARADocumentControllerInterface, createAudioSource),
            "createAudioSource",
        )?
    };
    Ok(unsafe { callback(controllerRef, hostRef, properties) })
}

pub(crate) unsafe fn update_audio_source_properties(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    properties: *const ARAAudioSourceProperties,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioSourceRef: ARAAudioSourceRef,
                properties: *const ARAAudioSourceProperties,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_UPDATE_AUDIO_SOURCE_PROPERTIES,
            ::std::mem::offset_of!(ARADocumentControllerInterface, updateAudioSourceProperties),
            "updateAudioSourceProperties",
        )?
    };
    unsafe { callback(controllerRef, audioSourceRef, properties) };
    Ok(())
}

pub(crate) unsafe fn update_audio_source_content(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    range: *const ARAContentTimeRange,
    flags: ARAContentUpdateFlags,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioSourceRef: ARAAudioSourceRef,
                range: *const ARAContentTimeRange,
                flags: ARAContentUpdateFlags,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_UPDATE_AUDIO_SOURCE_CONTENT,
            ::std::mem::offset_of!(ARADocumentControllerInterface, updateAudioSourceContent),
            "updateAudioSourceContent",
        )?
    };
    unsafe { callback(controllerRef, audioSourceRef, range, flags) };
    Ok(())
}

pub(crate) unsafe fn enable_audio_source_samples_access(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    enable: ARABool,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioSourceRef: ARAAudioSourceRef,
                enable: ARABool,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_ENABLE_AUDIO_SOURCE_SAMPLES_ACCESS,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                enableAudioSourceSamplesAccess
            ),
            "enableAudioSourceSamplesAccess",
        )?
    };
    unsafe { callback(controllerRef, audioSourceRef, enable) };
    Ok(())
}

pub(crate) unsafe fn deactivate_audio_source_for_undo_history(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    deactivate: ARABool,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioSourceRef: ARAAudioSourceRef,
                deactivate: ARABool,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_DEACTIVATE_AUDIO_SOURCE_FOR_UNDO_HISTORY,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                deactivateAudioSourceForUndoHistory
            ),
            "deactivateAudioSourceForUndoHistory",
        )?
    };
    unsafe { callback(controllerRef, audioSourceRef, deactivate) };
    Ok(())
}

pub(crate) unsafe fn destroy_audio_source(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioSourceRef: ARAAudioSourceRef,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_DESTROY_AUDIO_SOURCE,
            ::std::mem::offset_of!(ARADocumentControllerInterface, destroyAudioSource),
            "destroyAudioSource",
        )?
    };
    unsafe { callback(controllerRef, audioSourceRef) };
    Ok(())
}

pub(crate) unsafe fn create_audio_modification(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    hostRef: ARAAudioModificationHostRef,
    properties: *const ARAAudioModificationProperties,
) -> Result<ARAAudioModificationRef, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioSourceRef: ARAAudioSourceRef,
                hostRef: ARAAudioModificationHostRef,
                properties: *const ARAAudioModificationProperties,
            ) -> ARAAudioModificationRef,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_CREATE_AUDIO_MODIFICATION,
            ::std::mem::offset_of!(ARADocumentControllerInterface, createAudioModification),
            "createAudioModification",
        )?
    };
    Ok(unsafe { callback(controllerRef, audioSourceRef, hostRef, properties) })
}

pub(crate) unsafe fn clone_audio_modification(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioModificationRef: ARAAudioModificationRef,
    hostRef: ARAAudioModificationHostRef,
    properties: *const ARAAudioModificationProperties,
) -> Result<ARAAudioModificationRef, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioModificationRef: ARAAudioModificationRef,
                hostRef: ARAAudioModificationHostRef,
                properties: *const ARAAudioModificationProperties,
            ) -> ARAAudioModificationRef,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_CLONE_AUDIO_MODIFICATION,
            ::std::mem::offset_of!(ARADocumentControllerInterface, cloneAudioModification),
            "cloneAudioModification",
        )?
    };
    Ok(unsafe { callback(controllerRef, audioModificationRef, hostRef, properties) })
}

pub(crate) unsafe fn update_audio_modification_properties(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioModificationRef: ARAAudioModificationRef,
    properties: *const ARAAudioModificationProperties,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioModificationRef: ARAAudioModificationRef,
                properties: *const ARAAudioModificationProperties,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_UPDATE_AUDIO_MODIFICATION_PROPERTIES,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                updateAudioModificationProperties
            ),
            "updateAudioModificationProperties",
        )?
    };
    unsafe { callback(controllerRef, audioModificationRef, properties) };
    Ok(())
}

pub(crate) unsafe fn deactivate_audio_modification_for_undo_history(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioModificationRef: ARAAudioModificationRef,
    deactivate: ARABool,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioModificationRef: ARAAudioModificationRef,
                deactivate: ARABool,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_DEACTIVATE_AUDIO_MODIFICATION_FOR_UNDO_HISTORY,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                deactivateAudioModificationForUndoHistory
            ),
            "deactivateAudioModificationForUndoHistory",
        )?
    };
    unsafe { callback(controllerRef, audioModificationRef, deactivate) };
    Ok(())
}

pub(crate) unsafe fn destroy_audio_modification(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioModificationRef: ARAAudioModificationRef,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioModificationRef: ARAAudioModificationRef,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_DESTROY_AUDIO_MODIFICATION,
            ::std::mem::offset_of!(ARADocumentControllerInterface, destroyAudioModification),
            "destroyAudioModification",
        )?
    };
    unsafe { callback(controllerRef, audioModificationRef) };
    Ok(())
}

pub(crate) unsafe fn create_playback_region(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioModificationRef: ARAAudioModificationRef,
    hostRef: ARAPlaybackRegionHostRef,
    properties: *const ARAPlaybackRegionProperties,
) -> Result<ARAPlaybackRegionRef, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioModificationRef: ARAAudioModificationRef,
                hostRef: ARAPlaybackRegionHostRef,
                properties: *const ARAPlaybackRegionProperties,
            ) -> ARAPlaybackRegionRef,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_CREATE_PLAYBACK_REGION,
            ::std::mem::offset_of!(ARADocumentControllerInterface, createPlaybackRegion),
            "createPlaybackRegion",
        )?
    };
    Ok(unsafe { callback(controllerRef, audioModificationRef, hostRef, properties) })
}

pub(crate) unsafe fn update_playback_region_properties(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    playbackRegionRef: ARAPlaybackRegionRef,
    properties: *const ARAPlaybackRegionProperties,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                playbackRegionRef: ARAPlaybackRegionRef,
                properties: *const ARAPlaybackRegionProperties,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_UPDATE_PLAYBACK_REGION_PROPERTIES,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                updatePlaybackRegionProperties
            ),
            "updatePlaybackRegionProperties",
        )?
    };
    unsafe { callback(controllerRef, playbackRegionRef, properties) };
    Ok(())
}

pub(crate) unsafe fn destroy_playback_region(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    playbackRegionRef: ARAPlaybackRegionRef,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                playbackRegionRef: ARAPlaybackRegionRef,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_DESTROY_PLAYBACK_REGION,
            ::std::mem::offset_of!(ARADocumentControllerInterface, destroyPlaybackRegion),
            "destroyPlaybackRegion",
        )?
    };
    unsafe { callback(controllerRef, playbackRegionRef) };
    Ok(())
}

pub(crate) unsafe fn is_audio_source_content_available(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    contentType: ARAContentType,
) -> Result<ARABool, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioSourceRef: ARAAudioSourceRef,
                contentType: ARAContentType,
            ) -> ARABool,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_IS_AUDIO_SOURCE_CONTENT_AVAILABLE,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                isAudioSourceContentAvailable
            ),
            "isAudioSourceContentAvailable",
        )?
    };
    Ok(unsafe { callback(controllerRef, audioSourceRef, contentType) })
}

pub(crate) unsafe fn is_audio_source_content_analysis_incomplete(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    contentType: ARAContentType,
) -> Result<ARABool, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioSourceRef: ARAAudioSourceRef,
                contentType: ARAContentType,
            ) -> ARABool,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_IS_AUDIO_SOURCE_CONTENT_ANALYSIS_INCOMPLETE,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                isAudioSourceContentAnalysisIncomplete
            ),
            "isAudioSourceContentAnalysisIncomplete",
        )?
    };
    Ok(unsafe { callback(controllerRef, audioSourceRef, contentType) })
}

pub(crate) unsafe fn request_audio_source_content_analysis(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    contentTypesCount: ARASize,
    contentTypes: *const ARAContentType,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioSourceRef: ARAAudioSourceRef,
                contentTypesCount: ARASize,
                contentTypes: *const ARAContentType,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_REQUEST_AUDIO_SOURCE_CONTENT_ANALYSIS,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                requestAudioSourceContentAnalysis
            ),
            "requestAudioSourceContentAnalysis",
        )?
    };
    unsafe {
        callback(
            controllerRef,
            audioSourceRef,
            contentTypesCount,
            contentTypes,
        )
    };
    Ok(())
}

pub(crate) unsafe fn get_audio_source_content_grade(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    contentType: ARAContentType,
) -> Result<ARAContentGrade, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioSourceRef: ARAAudioSourceRef,
                contentType: ARAContentType,
            ) -> ARAContentGrade,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_AUDIO_SOURCE_CONTENT_GRADE,
            ::std::mem::offset_of!(ARADocumentControllerInterface, getAudioSourceContentGrade),
            "getAudioSourceContentGrade",
        )?
    };
    Ok(unsafe { callback(controllerRef, audioSourceRef, contentType) })
}

pub(crate) unsafe fn create_audio_source_content_reader(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    contentType: ARAContentType,
    range: *const ARAContentTimeRange,
) -> Result<ARAContentReaderRef, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioSourceRef: ARAAudioSourceRef,
                contentType: ARAContentType,
                range: *const ARAContentTimeRange,
            ) -> ARAContentReaderRef,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_CREATE_AUDIO_SOURCE_CONTENT_READER,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                createAudioSourceContentReader
            ),
            "createAudioSourceContentReader",
        )?
    };
    Ok(unsafe { callback(controllerRef, audioSourceRef, contentType, range) })
}

pub(crate) unsafe fn is_audio_modification_content_available(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioModificationRef: ARAAudioModificationRef,
    contentType: ARAContentType,
) -> Result<ARABool, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioModificationRef: ARAAudioModificationRef,
                contentType: ARAContentType,
            ) -> ARABool,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_IS_AUDIO_MODIFICATION_CONTENT_AVAILABLE,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                isAudioModificationContentAvailable
            ),
            "isAudioModificationContentAvailable",
        )?
    };
    Ok(unsafe { callback(controllerRef, audioModificationRef, contentType) })
}

pub(crate) unsafe fn get_audio_modification_content_grade(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioModificationRef: ARAAudioModificationRef,
    contentType: ARAContentType,
) -> Result<ARAContentGrade, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioModificationRef: ARAAudioModificationRef,
                contentType: ARAContentType,
            ) -> ARAContentGrade,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_AUDIO_MODIFICATION_CONTENT_GRADE,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                getAudioModificationContentGrade
            ),
            "getAudioModificationContentGrade",
        )?
    };
    Ok(unsafe { callback(controllerRef, audioModificationRef, contentType) })
}

pub(crate) unsafe fn create_audio_modification_content_reader(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioModificationRef: ARAAudioModificationRef,
    contentType: ARAContentType,
    range: *const ARAContentTimeRange,
) -> Result<ARAContentReaderRef, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioModificationRef: ARAAudioModificationRef,
                contentType: ARAContentType,
                range: *const ARAContentTimeRange,
            ) -> ARAContentReaderRef,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_CREATE_AUDIO_MODIFICATION_CONTENT_READER,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                createAudioModificationContentReader
            ),
            "createAudioModificationContentReader",
        )?
    };
    Ok(unsafe { callback(controllerRef, audioModificationRef, contentType, range) })
}

pub(crate) unsafe fn is_playback_region_content_available(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    playbackRegionRef: ARAPlaybackRegionRef,
    contentType: ARAContentType,
) -> Result<ARABool, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                playbackRegionRef: ARAPlaybackRegionRef,
                contentType: ARAContentType,
            ) -> ARABool,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_IS_PLAYBACK_REGION_CONTENT_AVAILABLE,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                isPlaybackRegionContentAvailable
            ),
            "isPlaybackRegionContentAvailable",
        )?
    };
    Ok(unsafe { callback(controllerRef, playbackRegionRef, contentType) })
}

pub(crate) unsafe fn get_playback_region_content_grade(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    playbackRegionRef: ARAPlaybackRegionRef,
    contentType: ARAContentType,
) -> Result<ARAContentGrade, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                playbackRegionRef: ARAPlaybackRegionRef,
                contentType: ARAContentType,
            ) -> ARAContentGrade,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_PLAYBACK_REGION_CONTENT_GRADE,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                getPlaybackRegionContentGrade
            ),
            "getPlaybackRegionContentGrade",
        )?
    };
    Ok(unsafe { callback(controllerRef, playbackRegionRef, contentType) })
}

pub(crate) unsafe fn create_playback_region_content_reader(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    playbackRegionRef: ARAPlaybackRegionRef,
    contentType: ARAContentType,
    range: *const ARAContentTimeRange,
) -> Result<ARAContentReaderRef, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                playbackRegionRef: ARAPlaybackRegionRef,
                contentType: ARAContentType,
                range: *const ARAContentTimeRange,
            ) -> ARAContentReaderRef,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_CREATE_PLAYBACK_REGION_CONTENT_READER,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                createPlaybackRegionContentReader
            ),
            "createPlaybackRegionContentReader",
        )?
    };
    Ok(unsafe { callback(controllerRef, playbackRegionRef, contentType, range) })
}

pub(crate) unsafe fn get_content_reader_event_count(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    contentReaderRef: ARAContentReaderRef,
) -> Result<ARAInt32, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                contentReaderRef: ARAContentReaderRef,
            ) -> ARAInt32,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_CONTENT_READER_EVENT_COUNT,
            ::std::mem::offset_of!(ARADocumentControllerInterface, getContentReaderEventCount),
            "getContentReaderEventCount",
        )?
    };
    Ok(unsafe { callback(controllerRef, contentReaderRef) })
}

pub(crate) unsafe fn get_content_reader_data_for_event(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    contentReaderRef: ARAContentReaderRef,
    eventIndex: ARAInt32,
) -> Result<*const ::std::os::raw::c_void, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                contentReaderRef: ARAContentReaderRef,
                eventIndex: ARAInt32,
            ) -> *const ::std::os::raw::c_void,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_CONTENT_READER_DATA_FOR_EVENT,
            ::std::mem::offset_of!(ARADocumentControllerInterface, getContentReaderDataForEvent),
            "getContentReaderDataForEvent",
        )?
    };
    Ok(unsafe { callback(controllerRef, contentReaderRef, eventIndex) })
}

pub(crate) unsafe fn destroy_content_reader(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    contentReaderRef: ARAContentReaderRef,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                contentReaderRef: ARAContentReaderRef,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_DESTROY_CONTENT_READER,
            ::std::mem::offset_of!(ARADocumentControllerInterface, destroyContentReader),
            "destroyContentReader",
        )?
    };
    unsafe { callback(controllerRef, contentReaderRef) };
    Ok(())
}

pub(crate) unsafe fn create_region_sequence(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    hostRef: ARARegionSequenceHostRef,
    properties: *const ARARegionSequenceProperties,
) -> Result<ARARegionSequenceRef, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                hostRef: ARARegionSequenceHostRef,
                properties: *const ARARegionSequenceProperties,
            ) -> ARARegionSequenceRef,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_CREATE_REGION_SEQUENCE,
            ::std::mem::offset_of!(ARADocumentControllerInterface, createRegionSequence),
            "createRegionSequence",
        )?
    };
    Ok(unsafe { callback(controllerRef, hostRef, properties) })
}

pub(crate) unsafe fn update_region_sequence_properties(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    regionSequenceRef: ARARegionSequenceRef,
    properties: *const ARARegionSequenceProperties,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                regionSequenceRef: ARARegionSequenceRef,
                properties: *const ARARegionSequenceProperties,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_UPDATE_REGION_SEQUENCE_PROPERTIES,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                updateRegionSequenceProperties
            ),
            "updateRegionSequenceProperties",
        )?
    };
    unsafe { callback(controllerRef, regionSequenceRef, properties) };
    Ok(())
}

pub(crate) unsafe fn destroy_region_sequence(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    regionSequenceRef: ARARegionSequenceRef,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                regionSequenceRef: ARARegionSequenceRef,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_DESTROY_REGION_SEQUENCE,
            ::std::mem::offset_of!(ARADocumentControllerInterface, destroyRegionSequence),
            "destroyRegionSequence",
        )?
    };
    unsafe { callback(controllerRef, regionSequenceRef) };
    Ok(())
}

pub(crate) unsafe fn get_playback_region_head_and_tail_time(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    playbackRegionRef: ARAPlaybackRegionRef,
    headTime: *mut ARATimeDuration,
    tailTime: *mut ARATimeDuration,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                playbackRegionRef: ARAPlaybackRegionRef,
                headTime: *mut ARATimeDuration,
                tailTime: *mut ARATimeDuration,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_PLAYBACK_REGION_HEAD_AND_TAIL_TIME,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                getPlaybackRegionHeadAndTailTime
            ),
            "getPlaybackRegionHeadAndTailTime",
        )?
    };
    unsafe { callback(controllerRef, playbackRegionRef, headTime, tailTime) };
    Ok(())
}

pub(crate) unsafe fn restore_objects_from_archive(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    archiveReaderHostRef: ARAArchiveReaderHostRef,
    filter: *const ARARestoreObjectsFilter,
) -> Result<ARABool, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                archiveReaderHostRef: ARAArchiveReaderHostRef,
                filter: *const ARARestoreObjectsFilter,
            ) -> ARABool,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_RESTORE_OBJECTS_FROM_ARCHIVE,
            ::std::mem::offset_of!(ARADocumentControllerInterface, restoreObjectsFromArchive),
            "restoreObjectsFromArchive",
        )?
    };
    Ok(unsafe { callback(controllerRef, archiveReaderHostRef, filter) })
}

pub(crate) unsafe fn store_objects_to_archive(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    archiveWriterHostRef: ARAArchiveWriterHostRef,
    filter: *const ARAStoreObjectsFilter,
) -> Result<ARABool, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                archiveWriterHostRef: ARAArchiveWriterHostRef,
                filter: *const ARAStoreObjectsFilter,
            ) -> ARABool,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_STORE_OBJECTS_TO_ARCHIVE,
            ::std::mem::offset_of!(ARADocumentControllerInterface, storeObjectsToArchive),
            "storeObjectsToArchive",
        )?
    };
    Ok(unsafe { callback(controllerRef, archiveWriterHostRef, filter) })
}

pub(crate) unsafe fn get_processing_algorithms_count(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
) -> Result<ARAInt32, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(controllerRef: ARADocumentControllerRef) -> ARAInt32,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_PROCESSING_ALGORITHMS_COUNT,
            ::std::mem::offset_of!(ARADocumentControllerInterface, getProcessingAlgorithmsCount),
            "getProcessingAlgorithmsCount",
        )?
    };
    Ok(unsafe { callback(controllerRef) })
}

pub(crate) unsafe fn get_processing_algorithm_properties(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    algorithmIndex: ARAInt32,
) -> Result<*const ARAProcessingAlgorithmProperties, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                algorithmIndex: ARAInt32,
            ) -> *const ARAProcessingAlgorithmProperties,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_PROCESSING_ALGORITHM_PROPERTIES,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                getProcessingAlgorithmProperties
            ),
            "getProcessingAlgorithmProperties",
        )?
    };
    Ok(unsafe { callback(controllerRef, algorithmIndex) })
}

pub(crate) unsafe fn get_processing_algorithm_for_audio_source(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
) -> Result<ARAInt32, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioSourceRef: ARAAudioSourceRef,
            ) -> ARAInt32,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_GET_PROCESSING_ALGORITHM_FOR_AUDIO_SOURCE,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                getProcessingAlgorithmForAudioSource
            ),
            "getProcessingAlgorithmForAudioSource",
        )?
    };
    Ok(unsafe { callback(controllerRef, audioSourceRef) })
}

pub(crate) unsafe fn request_processing_algorithm_for_audio_source(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioSourceRef: ARAAudioSourceRef,
    algorithmIndex: ARAInt32,
) -> Result<(), AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                audioSourceRef: ARAAudioSourceRef,
                algorithmIndex: ARAInt32,
            ),
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_REQUEST_PROCESSING_ALGORITHM_FOR_AUDIO_SOURCE,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                requestProcessingAlgorithmForAudioSource
            ),
            "requestProcessingAlgorithmForAudioSource",
        )?
    };
    unsafe { callback(controllerRef, audioSourceRef, algorithmIndex) };
    Ok(())
}

pub(crate) unsafe fn is_licensed_for_capabilities(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    runModalActivationDialogIfNeeded: ARABool,
    contentTypesCount: ARASize,
    contentTypes: *const ARAContentType,
    transformationFlags: ARAPlaybackTransformationFlags,
) -> Result<ARABool, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                runModalActivationDialogIfNeeded: ARABool,
                contentTypesCount: ARASize,
                contentTypes: *const ARAContentType,
                transformationFlags: ARAPlaybackTransformationFlags,
            ) -> ARABool,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_IS_LICENSED_FOR_CAPABILITIES,
            ::std::mem::offset_of!(ARADocumentControllerInterface, isLicensedForCapabilities),
            "isLicensedForCapabilities",
        )?
    };
    Ok(unsafe {
        callback(
            controllerRef,
            runModalActivationDialogIfNeeded,
            contentTypesCount,
            contentTypes,
            transformationFlags,
        )
    })
}

pub(crate) unsafe fn store_audio_source_to_audio_file_chunk(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    archiveWriterHostRef: ARAArchiveWriterHostRef,
    audioSourceRef: ARAAudioSourceRef,
    documentArchiveID: *mut ARAPersistentID,
    openAutomatically: *mut ARABool,
) -> Result<ARABool, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<
            unsafe extern "C" fn(
                controllerRef: ARADocumentControllerRef,
                archiveWriterHostRef: ARAArchiveWriterHostRef,
                audioSourceRef: ARAAudioSourceRef,
                documentArchiveID: *mut ARAPersistentID,
                openAutomatically: *mut ARABool,
            ) -> ARABool,
        >(
            interface,
            layout::ARADOCUMENT_CONTROLLER_INTERFACE_STORE_AUDIO_SOURCE_TO_AUDIO_FILE_CHUNK,
            ::std::mem::offset_of!(
                ARADocumentControllerInterface,
                storeAudioSourceToAudioFileChunk
            ),
            "storeAudioSourceToAudioFileChunk",
        )?
    };
    Ok(unsafe {
        callback(
            controllerRef,
            archiveWriterHostRef,
            audioSourceRef,
            documentArchiveID,
            openAutomatically,
        )
    })
}

pub(crate) unsafe fn is_audio_modification_preserving_audio_source_signal(
    interface: *const ARADocumentControllerInterface,
    controllerRef: ARADocumentControllerRef,
    audioModificationRef: ARAAudioModificationRef,
) -> Result<ARABool, AraError> {
    let callback = unsafe {
        super::dispatch::callback::<unsafe extern "C" fn(
            controllerRef: ARADocumentControllerRef,
            audioModificationRef: ARAAudioModificationRef,
        ) -> ARABool>(interface, layout::ARADOCUMENT_CONTROLLER_INTERFACE_IS_AUDIO_MODIFICATION_PRESERVING_AUDIO_SOURCE_SIGNAL, ::std::mem::offset_of!(ARADocumentControllerInterface, isAudioModificationPreservingAudioSourceSignal), "isAudioModificationPreservingAudioSourceSignal")?
    };
    Ok(unsafe { callback(controllerRef, audioModificationRef) })
}

impl super::DocumentController<'_, '_> {
    pub(crate) unsafe fn raw_get_factory(&mut self) -> Result<*const ARAFactory, AraError> {
        unsafe { get_factory(self.interface_ptr(), self.as_raw_ref()) }
    }

    pub(crate) unsafe fn raw_begin_editing(&mut self) -> Result<(), AraError> {
        unsafe { begin_editing(self.interface_ptr(), self.as_raw_ref()) }
    }

    pub(crate) unsafe fn raw_end_editing(&mut self) -> Result<(), AraError> {
        unsafe { end_editing(self.interface_ptr(), self.as_raw_ref()) }
    }

    pub(crate) unsafe fn raw_notify_model_updates(&mut self) -> Result<(), AraError> {
        unsafe { notify_model_updates(self.interface_ptr(), self.as_raw_ref()) }
    }

    pub(crate) unsafe fn raw_begin_restoring_document_from_archive(
        &mut self,
        archiveReaderHostRef: ARAArchiveReaderHostRef,
    ) -> Result<ARABool, AraError> {
        unsafe {
            begin_restoring_document_from_archive(
                self.interface_ptr(),
                self.as_raw_ref(),
                archiveReaderHostRef,
            )
        }
    }

    pub(crate) unsafe fn raw_end_restoring_document_from_archive(
        &mut self,
        archiveReaderHostRef: ARAArchiveReaderHostRef,
    ) -> Result<ARABool, AraError> {
        unsafe {
            end_restoring_document_from_archive(
                self.interface_ptr(),
                self.as_raw_ref(),
                archiveReaderHostRef,
            )
        }
    }

    pub(crate) unsafe fn raw_store_document_to_archive(
        &mut self,
        archiveWriterHostRef: ARAArchiveWriterHostRef,
    ) -> Result<ARABool, AraError> {
        unsafe {
            store_document_to_archive(
                self.interface_ptr(),
                self.as_raw_ref(),
                archiveWriterHostRef,
            )
        }
    }

    pub(crate) unsafe fn raw_update_document_properties(
        &mut self,
        properties: *const ARADocumentProperties,
    ) -> Result<(), AraError> {
        unsafe { update_document_properties(self.interface_ptr(), self.as_raw_ref(), properties) }
    }

    pub(crate) unsafe fn raw_create_musical_context(
        &mut self,
        hostRef: ARAMusicalContextHostRef,
        properties: *const ARAMusicalContextProperties,
    ) -> Result<ARAMusicalContextRef, AraError> {
        unsafe {
            create_musical_context(self.interface_ptr(), self.as_raw_ref(), hostRef, properties)
        }
    }

    pub(crate) unsafe fn raw_update_musical_context_properties(
        &mut self,
        musicalContextRef: ARAMusicalContextRef,
        properties: *const ARAMusicalContextProperties,
    ) -> Result<(), AraError> {
        unsafe {
            update_musical_context_properties(
                self.interface_ptr(),
                self.as_raw_ref(),
                musicalContextRef,
                properties,
            )
        }
    }

    pub(crate) unsafe fn raw_update_musical_context_content(
        &mut self,
        musicalContextRef: ARAMusicalContextRef,
        range: *const ARAContentTimeRange,
        flags: ARAContentUpdateFlags,
    ) -> Result<(), AraError> {
        unsafe {
            update_musical_context_content(
                self.interface_ptr(),
                self.as_raw_ref(),
                musicalContextRef,
                range,
                flags,
            )
        }
    }

    pub(crate) unsafe fn raw_destroy_musical_context(
        &mut self,
        musicalContextRef: ARAMusicalContextRef,
    ) -> Result<(), AraError> {
        unsafe {
            destroy_musical_context(self.interface_ptr(), self.as_raw_ref(), musicalContextRef)
        }
    }

    pub(crate) unsafe fn raw_create_audio_source(
        &mut self,
        hostRef: ARAAudioSourceHostRef,
        properties: *const ARAAudioSourceProperties,
    ) -> Result<ARAAudioSourceRef, AraError> {
        unsafe { create_audio_source(self.interface_ptr(), self.as_raw_ref(), hostRef, properties) }
    }

    pub(crate) unsafe fn raw_update_audio_source_properties(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        properties: *const ARAAudioSourceProperties,
    ) -> Result<(), AraError> {
        unsafe {
            update_audio_source_properties(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioSourceRef,
                properties,
            )
        }
    }

    pub(crate) unsafe fn raw_update_audio_source_content(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        range: *const ARAContentTimeRange,
        flags: ARAContentUpdateFlags,
    ) -> Result<(), AraError> {
        unsafe {
            update_audio_source_content(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioSourceRef,
                range,
                flags,
            )
        }
    }

    pub(crate) unsafe fn raw_enable_audio_source_samples_access(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        enable: ARABool,
    ) -> Result<(), AraError> {
        unsafe {
            enable_audio_source_samples_access(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioSourceRef,
                enable,
            )
        }
    }

    pub(crate) unsafe fn raw_deactivate_audio_source_for_undo_history(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        deactivate: ARABool,
    ) -> Result<(), AraError> {
        unsafe {
            deactivate_audio_source_for_undo_history(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioSourceRef,
                deactivate,
            )
        }
    }

    pub(crate) unsafe fn raw_destroy_audio_source(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
    ) -> Result<(), AraError> {
        unsafe { destroy_audio_source(self.interface_ptr(), self.as_raw_ref(), audioSourceRef) }
    }

    pub(crate) unsafe fn raw_create_audio_modification(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        hostRef: ARAAudioModificationHostRef,
        properties: *const ARAAudioModificationProperties,
    ) -> Result<ARAAudioModificationRef, AraError> {
        unsafe {
            create_audio_modification(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioSourceRef,
                hostRef,
                properties,
            )
        }
    }

    pub(crate) unsafe fn raw_clone_audio_modification(
        &mut self,
        audioModificationRef: ARAAudioModificationRef,
        hostRef: ARAAudioModificationHostRef,
        properties: *const ARAAudioModificationProperties,
    ) -> Result<ARAAudioModificationRef, AraError> {
        unsafe {
            clone_audio_modification(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioModificationRef,
                hostRef,
                properties,
            )
        }
    }

    pub(crate) unsafe fn raw_update_audio_modification_properties(
        &mut self,
        audioModificationRef: ARAAudioModificationRef,
        properties: *const ARAAudioModificationProperties,
    ) -> Result<(), AraError> {
        unsafe {
            update_audio_modification_properties(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioModificationRef,
                properties,
            )
        }
    }

    pub(crate) unsafe fn raw_deactivate_audio_modification_for_undo_history(
        &mut self,
        audioModificationRef: ARAAudioModificationRef,
        deactivate: ARABool,
    ) -> Result<(), AraError> {
        unsafe {
            deactivate_audio_modification_for_undo_history(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioModificationRef,
                deactivate,
            )
        }
    }

    pub(crate) unsafe fn raw_destroy_audio_modification(
        &mut self,
        audioModificationRef: ARAAudioModificationRef,
    ) -> Result<(), AraError> {
        unsafe {
            destroy_audio_modification(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioModificationRef,
            )
        }
    }

    pub(crate) unsafe fn raw_create_playback_region(
        &mut self,
        audioModificationRef: ARAAudioModificationRef,
        hostRef: ARAPlaybackRegionHostRef,
        properties: *const ARAPlaybackRegionProperties,
    ) -> Result<ARAPlaybackRegionRef, AraError> {
        unsafe {
            create_playback_region(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioModificationRef,
                hostRef,
                properties,
            )
        }
    }

    pub(crate) unsafe fn raw_update_playback_region_properties(
        &mut self,
        playbackRegionRef: ARAPlaybackRegionRef,
        properties: *const ARAPlaybackRegionProperties,
    ) -> Result<(), AraError> {
        unsafe {
            update_playback_region_properties(
                self.interface_ptr(),
                self.as_raw_ref(),
                playbackRegionRef,
                properties,
            )
        }
    }

    pub(crate) unsafe fn raw_destroy_playback_region(
        &mut self,
        playbackRegionRef: ARAPlaybackRegionRef,
    ) -> Result<(), AraError> {
        unsafe {
            destroy_playback_region(self.interface_ptr(), self.as_raw_ref(), playbackRegionRef)
        }
    }

    pub(crate) unsafe fn raw_is_audio_source_content_available(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        contentType: ARAContentType,
    ) -> Result<ARABool, AraError> {
        unsafe {
            is_audio_source_content_available(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioSourceRef,
                contentType,
            )
        }
    }

    pub(crate) unsafe fn raw_is_audio_source_content_analysis_incomplete(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        contentType: ARAContentType,
    ) -> Result<ARABool, AraError> {
        unsafe {
            is_audio_source_content_analysis_incomplete(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioSourceRef,
                contentType,
            )
        }
    }

    pub(crate) unsafe fn raw_request_audio_source_content_analysis(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        contentTypesCount: ARASize,
        contentTypes: *const ARAContentType,
    ) -> Result<(), AraError> {
        unsafe {
            request_audio_source_content_analysis(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioSourceRef,
                contentTypesCount,
                contentTypes,
            )
        }
    }

    pub(crate) unsafe fn raw_get_audio_source_content_grade(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        contentType: ARAContentType,
    ) -> Result<ARAContentGrade, AraError> {
        unsafe {
            get_audio_source_content_grade(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioSourceRef,
                contentType,
            )
        }
    }

    pub(crate) unsafe fn raw_create_audio_source_content_reader(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        contentType: ARAContentType,
        range: *const ARAContentTimeRange,
    ) -> Result<ARAContentReaderRef, AraError> {
        unsafe {
            create_audio_source_content_reader(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioSourceRef,
                contentType,
                range,
            )
        }
    }

    pub(crate) unsafe fn raw_is_audio_modification_content_available(
        &mut self,
        audioModificationRef: ARAAudioModificationRef,
        contentType: ARAContentType,
    ) -> Result<ARABool, AraError> {
        unsafe {
            is_audio_modification_content_available(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioModificationRef,
                contentType,
            )
        }
    }

    pub(crate) unsafe fn raw_get_audio_modification_content_grade(
        &mut self,
        audioModificationRef: ARAAudioModificationRef,
        contentType: ARAContentType,
    ) -> Result<ARAContentGrade, AraError> {
        unsafe {
            get_audio_modification_content_grade(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioModificationRef,
                contentType,
            )
        }
    }

    pub(crate) unsafe fn raw_create_audio_modification_content_reader(
        &mut self,
        audioModificationRef: ARAAudioModificationRef,
        contentType: ARAContentType,
        range: *const ARAContentTimeRange,
    ) -> Result<ARAContentReaderRef, AraError> {
        unsafe {
            create_audio_modification_content_reader(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioModificationRef,
                contentType,
                range,
            )
        }
    }

    pub(crate) unsafe fn raw_is_playback_region_content_available(
        &mut self,
        playbackRegionRef: ARAPlaybackRegionRef,
        contentType: ARAContentType,
    ) -> Result<ARABool, AraError> {
        unsafe {
            is_playback_region_content_available(
                self.interface_ptr(),
                self.as_raw_ref(),
                playbackRegionRef,
                contentType,
            )
        }
    }

    pub(crate) unsafe fn raw_get_playback_region_content_grade(
        &mut self,
        playbackRegionRef: ARAPlaybackRegionRef,
        contentType: ARAContentType,
    ) -> Result<ARAContentGrade, AraError> {
        unsafe {
            get_playback_region_content_grade(
                self.interface_ptr(),
                self.as_raw_ref(),
                playbackRegionRef,
                contentType,
            )
        }
    }

    pub(crate) unsafe fn raw_create_playback_region_content_reader(
        &mut self,
        playbackRegionRef: ARAPlaybackRegionRef,
        contentType: ARAContentType,
        range: *const ARAContentTimeRange,
    ) -> Result<ARAContentReaderRef, AraError> {
        unsafe {
            create_playback_region_content_reader(
                self.interface_ptr(),
                self.as_raw_ref(),
                playbackRegionRef,
                contentType,
                range,
            )
        }
    }

    pub(crate) unsafe fn raw_get_content_reader_event_count(
        &mut self,
        contentReaderRef: ARAContentReaderRef,
    ) -> Result<ARAInt32, AraError> {
        unsafe {
            get_content_reader_event_count(
                self.interface_ptr(),
                self.as_raw_ref(),
                contentReaderRef,
            )
        }
    }

    pub(crate) unsafe fn raw_get_content_reader_data_for_event(
        &mut self,
        contentReaderRef: ARAContentReaderRef,
        eventIndex: ARAInt32,
    ) -> Result<*const ::std::os::raw::c_void, AraError> {
        unsafe {
            get_content_reader_data_for_event(
                self.interface_ptr(),
                self.as_raw_ref(),
                contentReaderRef,
                eventIndex,
            )
        }
    }

    pub(crate) unsafe fn raw_destroy_content_reader(
        &mut self,
        contentReaderRef: ARAContentReaderRef,
    ) -> Result<(), AraError> {
        unsafe { destroy_content_reader(self.interface_ptr(), self.as_raw_ref(), contentReaderRef) }
    }

    pub(crate) unsafe fn raw_create_region_sequence(
        &mut self,
        hostRef: ARARegionSequenceHostRef,
        properties: *const ARARegionSequenceProperties,
    ) -> Result<ARARegionSequenceRef, AraError> {
        unsafe {
            create_region_sequence(self.interface_ptr(), self.as_raw_ref(), hostRef, properties)
        }
    }

    pub(crate) unsafe fn raw_update_region_sequence_properties(
        &mut self,
        regionSequenceRef: ARARegionSequenceRef,
        properties: *const ARARegionSequenceProperties,
    ) -> Result<(), AraError> {
        unsafe {
            update_region_sequence_properties(
                self.interface_ptr(),
                self.as_raw_ref(),
                regionSequenceRef,
                properties,
            )
        }
    }

    pub(crate) unsafe fn raw_destroy_region_sequence(
        &mut self,
        regionSequenceRef: ARARegionSequenceRef,
    ) -> Result<(), AraError> {
        unsafe {
            destroy_region_sequence(self.interface_ptr(), self.as_raw_ref(), regionSequenceRef)
        }
    }

    pub(crate) unsafe fn raw_get_playback_region_head_and_tail_time(
        &mut self,
        playbackRegionRef: ARAPlaybackRegionRef,
        headTime: *mut ARATimeDuration,
        tailTime: *mut ARATimeDuration,
    ) -> Result<(), AraError> {
        unsafe {
            get_playback_region_head_and_tail_time(
                self.interface_ptr(),
                self.as_raw_ref(),
                playbackRegionRef,
                headTime,
                tailTime,
            )
        }
    }

    pub(crate) unsafe fn raw_restore_objects_from_archive(
        &mut self,
        archiveReaderHostRef: ARAArchiveReaderHostRef,
        filter: *const ARARestoreObjectsFilter,
    ) -> Result<ARABool, AraError> {
        unsafe {
            restore_objects_from_archive(
                self.interface_ptr(),
                self.as_raw_ref(),
                archiveReaderHostRef,
                filter,
            )
        }
    }

    pub(crate) unsafe fn raw_store_objects_to_archive(
        &mut self,
        archiveWriterHostRef: ARAArchiveWriterHostRef,
        filter: *const ARAStoreObjectsFilter,
    ) -> Result<ARABool, AraError> {
        unsafe {
            store_objects_to_archive(
                self.interface_ptr(),
                self.as_raw_ref(),
                archiveWriterHostRef,
                filter,
            )
        }
    }

    pub(crate) unsafe fn raw_get_processing_algorithms_count(
        &mut self,
    ) -> Result<ARAInt32, AraError> {
        unsafe { get_processing_algorithms_count(self.interface_ptr(), self.as_raw_ref()) }
    }

    pub(crate) unsafe fn raw_get_processing_algorithm_properties(
        &mut self,
        algorithmIndex: ARAInt32,
    ) -> Result<*const ARAProcessingAlgorithmProperties, AraError> {
        unsafe {
            get_processing_algorithm_properties(
                self.interface_ptr(),
                self.as_raw_ref(),
                algorithmIndex,
            )
        }
    }

    pub(crate) unsafe fn raw_get_processing_algorithm_for_audio_source(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
    ) -> Result<ARAInt32, AraError> {
        unsafe {
            get_processing_algorithm_for_audio_source(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioSourceRef,
            )
        }
    }

    pub(crate) unsafe fn raw_request_processing_algorithm_for_audio_source(
        &mut self,
        audioSourceRef: ARAAudioSourceRef,
        algorithmIndex: ARAInt32,
    ) -> Result<(), AraError> {
        unsafe {
            request_processing_algorithm_for_audio_source(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioSourceRef,
                algorithmIndex,
            )
        }
    }

    pub(crate) unsafe fn raw_is_licensed_for_capabilities(
        &mut self,
        runModalActivationDialogIfNeeded: ARABool,
        contentTypesCount: ARASize,
        contentTypes: *const ARAContentType,
        transformationFlags: ARAPlaybackTransformationFlags,
    ) -> Result<ARABool, AraError> {
        unsafe {
            is_licensed_for_capabilities(
                self.interface_ptr(),
                self.as_raw_ref(),
                runModalActivationDialogIfNeeded,
                contentTypesCount,
                contentTypes,
                transformationFlags,
            )
        }
    }

    pub(crate) unsafe fn raw_store_audio_source_to_audio_file_chunk(
        &mut self,
        archiveWriterHostRef: ARAArchiveWriterHostRef,
        audioSourceRef: ARAAudioSourceRef,
        documentArchiveID: *mut ARAPersistentID,
        openAutomatically: *mut ARABool,
    ) -> Result<ARABool, AraError> {
        unsafe {
            store_audio_source_to_audio_file_chunk(
                self.interface_ptr(),
                self.as_raw_ref(),
                archiveWriterHostRef,
                audioSourceRef,
                documentArchiveID,
                openAutomatically,
            )
        }
    }

    pub(crate) unsafe fn raw_is_audio_modification_preserving_audio_source_signal(
        &mut self,
        audioModificationRef: ARAAudioModificationRef,
    ) -> Result<ARABool, AraError> {
        unsafe {
            is_audio_modification_preserving_audio_source_signal(
                self.interface_ptr(),
                self.as_raw_ref(),
                audioModificationRef,
            )
        }
    }
}
