export type AppMenuItem =
  | {
      type?: "item";
      id: string;
      label: string;
      accelerator?: string;
      icon?: string;
      dot?: string;       // CSS color for a small dot prefix (e.g. track colors)
      enabled?: boolean;
      checked?: boolean;
      danger?: boolean;
      role?: string;
      action?: string;
      description?: string;
    }
  | {
      type: "separator";
      id: string;
    }
  | {
      type: "submenu";
      id: string;
      label: string;
      icon?: string;
      enabled?: boolean;
      children: AppMenuItem[];
    };

export type AppMenuGroup = {
  id: string;
  label: string;
  children: AppMenuItem[];
};

export const APP_MENUS: AppMenuGroup[] = [
  {
    id: "file",
    label: "File",
    children: [
      {
        id: "file.new_project",
        label: "New Project",
        accelerator: "Ctrl+N",
        icon: "file-plus",
        action: "project:new",
        description: "Create a new empty project",
      },
      {
        id: "file.new_project_from_template",
        label: "New Project from Template",
        accelerator: "Ctrl+Shift+N",
        icon: "layout-template",
        action: "project:new-from-template",
      },
      {
        id: "file.open_project",
        label: "Open Project...",
        accelerator: "Ctrl+O",
        icon: "folder-open",
        action: "project:open",
      },
      {
        id: "file.open_recent",
        type: "submenu",
        label: "Open Recent",
        icon: "history",
        children: [
          {
            id: "file.open_recent.empty",
            label: "No Recent Projects",
            enabled: false,
            action: "noop",
          },
          {
            id: "file.open_recent.clear",
            label: "Clear Recent Projects",
            action: "project:recent-clear",
          },
        ],
      },
      {
        type: "separator",
        id: "file.sep.project",
      },
      {
        id: "file.save",
        label: "Save",
        accelerator: "Ctrl+S",
        icon: "save",
        action: "project:save",
      },
      {
        id: "file.save_as",
        label: "Save As...",
        accelerator: "Ctrl+Shift+S",
        icon: "save-all",
        action: "project:save-as",
      },
      {
        id: "file.save_copy",
        label: "Save a Copy...",
        icon: "copy",
        action: "project:save-copy",
      },
      {
        id: "file.snapshot",
        label: "Create Snapshot",
        accelerator: "Ctrl+Alt+S",
        icon: "camera",
        action: "project:snapshot",
      },
      {
        id: "file.revert_to_saved",
        label: "Revert to Saved",
        icon: "rotate-ccw",
        action: "project:revert",
      },
      {
        type: "separator",
        id: "file.sep.import",
      },
      {
        id: "file.import_audio",
        label: "Import Audio...",
        accelerator: "Ctrl+I",
        icon: "music",
        action: "file:import-audio",
      },
      {
        id: "file.import_midi",
        label: "Import MIDI...",
        icon: "piano",
        action: "file:import-midi",
        enabled: false,
      },
      {
        id: "file.import_stems",
        label: "Import Stems...",
        icon: "layers",
        action: "file:import-stems",
      },
      {
        id: "file.import_folder",
        label: "Import Folder...",
        icon: "folder-input",
        action: "file:import-folder",
      },
      {
        id: "file.import_session",
        label: "Import Session Data...",
        icon: "database",
        action: "file:import-session",
      },
      {
        type: "separator",
        id: "file.sep.export",
      },
      {
        id: "file.export_audio",
        label: "Export Audio...",
        accelerator: "Ctrl+E",
        icon: "download",
        action: "file:export-audio",
      },
      {
        id: "file.export_stems",
        label: "Export Stems...",
        accelerator: "Ctrl+Shift+E",
        icon: "files",
        action: "file:export-stems",
      },
      {
        id: "file.export_loop",
        label: "Export Loop Region...",
        icon: "repeat",
        action: "file:export-loop",
      },
      {
        id: "file.export_project_archive",
        label: "Export Project Archive...",
        icon: "archive",
        action: "file:export-project-archive",
      },
      {
        id: "file.bounce_selection",
        label: "Bounce Selection...",
        icon: "waveform",
        action: "file:bounce-selection",
      },
      {
        type: "separator",
        id: "file.sep.cloud",
      },
      {
        id: "file.cloud_sync",
        label: "Sync Project to Cloud",
        icon: "cloud-upload",
        action: "cloud:sync",
      },
      {
        id: "file.share_project",
        label: "Share Project...",
        icon: "share-2",
        action: "cloud:share-project",
      },
      {
        id: "file.project_versions",
        label: "Version History...",
        icon: "git-branch",
        action: "cloud:versions",
      },
      {
        type: "separator",
        id: "file.sep.close",
      },
      {
        id: "file.close_project",
        label: "Close Project",
        accelerator: "Ctrl+W",
        icon: "x",
        action: "project:close",
      },
      {
        id: "file.quit",
        label: "Quit",
        accelerator: "Alt+F4",
        icon: "power",
        role: "quit",
        action: "app:quit",
      },
    ],
  },

  {
    id: "edit",
    label: "Edit",
    children: [
      {
        id: "edit.undo",
        label: "Undo",
        accelerator: "Ctrl+Z",
        icon: "undo-2",
        action: "edit:undo",
      },
      {
        id: "edit.redo",
        label: "Redo",
        accelerator: "Ctrl+Y",
        icon: "redo-2",
        action: "edit:redo",
      },
      {
        type: "separator",
        id: "edit.sep.clipboard",
      },
      {
        id: "edit.cut",
        label: "Cut",
        accelerator: "Ctrl+X",
        icon: "scissors",
        action: "edit:cut",
      },
      {
        id: "edit.copy",
        label: "Copy",
        accelerator: "Ctrl+C",
        icon: "copy",
        action: "edit:copy",
      },
      {
        id: "edit.paste",
        label: "Paste",
        accelerator: "Ctrl+V",
        icon: "clipboard",
        action: "edit:paste",
      },
      {
        id: "edit.duplicate",
        label: "Duplicate",
        accelerator: "Ctrl+D",
        icon: "copy-plus",
        action: "edit:duplicate",
      },
      {
        id: "edit.delete",
        label: "Delete",
        accelerator: "Delete",
        icon: "trash-2",
        danger: true,
        action: "edit:delete",
      },
      {
        type: "separator",
        id: "edit.sep.select",
      },
      {
        id: "edit.select_all",
        label: "Select All",
        accelerator: "Ctrl+A",
        icon: "scan",
        action: "edit:select-all",
      },
      {
        id: "edit.deselect_all",
        label: "Deselect All",
        accelerator: "Esc",
        icon: "scan-x",
        action: "edit:deselect-all",
      },
      {
        id: "edit.select_track_clips",
        label: "Select All Clips on Track",
        icon: "mouse-pointer-2",
        action: "edit:select-track-clips",
      },
      {
        id: "edit.select_loop_range",
        label: "Select Loop Range",
        icon: "repeat",
        action: "edit:select-loop-range",
      },
      {
        type: "separator",
        id: "edit.sep.timeline",
      },
      {
        id: "edit.split_clip",
        label: "Split Clip at Playhead",
        accelerator: "S",
        icon: "split",
        action: "clip:split-at-playhead",
      },
      {
        id: "edit.trim_start_to_playhead",
        label: "Trim Start to Playhead",
        icon: "move-left",
        action: "clip:trim-start-to-playhead",
      },
      {
        id: "edit.trim_end_to_playhead",
        label: "Trim End to Playhead",
        icon: "move-right",
        action: "clip:trim-end-to-playhead",
      },
      {
        id: "edit.crop_to_selection",
        label: "Crop to Selection",
        icon: "crop",
        action: "clip:crop-to-selection",
      },
      {
        id: "edit.consolidate",
        label: "Consolidate Clip",
        accelerator: "Ctrl+J",
        icon: "combine",
        action: "clip:consolidate",
      },
      {
        id: "edit.reverse_clip",
        label: "Reverse Clip",
        icon: "refresh-ccw",
        action: "clip:reverse",
      },
      {
        type: "separator",
        id: "edit.sep.snap",
      },
      {
        id: "edit.snap_to_grid",
        label: "Snap to Grid",
        accelerator: "Ctrl+G",
        icon: "magnet",
        checked: true,
        action: "timeline:toggle-snap",
      },
      {
        id: "edit.snap_settings",
        type: "submenu",
        label: "Snap Settings",
        icon: "grid-3x3",
        children: [
          {
            id: "edit.snap.bar",
            label: "Bar",
            action: "timeline:set-snap-bar",
          },
          {
            id: "edit.snap.beat",
            label: "Beat",
            checked: true,
            action: "timeline:set-snap-beat",
          },
          {
            id: "edit.snap.eighth",
            label: "1/8 Note",
            action: "timeline:set-snap-eighth",
          },
          {
            id: "edit.snap.sixteenth",
            label: "1/16 Note",
            action: "timeline:set-snap-sixteenth",
          },
          {
            id: "edit.snap.thirty_second",
            label: "1/32 Note",
            action: "timeline:set-snap-thirty-second",
          },
          {
            id: "edit.snap.off",
            label: "Off",
            action: "timeline:set-snap-off",
          },
        ],
      },
      {
        type: "separator",
        id: "edit.sep.preferences",
      },
      {
        id: "edit.preferences",
        label: "Preferences...",
        accelerator: "Ctrl+,",
        icon: "settings",
        action: "app:preferences",
      },
    ],
  },

  {
    id: "midi",
    label: "MIDI",
    children: [
      {
        id: "midi.select_all",
        label: "Select All Notes",
        accelerator: "Ctrl+A",
        icon: "scan",
        action: "midi:select-all",
        description: "Select all notes in the MIDI editor",
      },
      {
        id: "midi.delete_selected",
        label: "Delete Selected Notes",
        accelerator: "Delete",
        icon: "trash-2",
        danger: true,
        action: "midi:delete-selected",
        description: "Delete selected MIDI notes",
      },
      {
        id: "midi.duplicate_selected",
        label: "Duplicate Selected Notes",
        accelerator: "Ctrl+D",
        icon: "copy-plus",
        action: "midi:duplicate-selected",
        description: "Duplicate selected MIDI notes",
      },
      {
        type: "separator",
        id: "midi.sep.quantize",
      },
      {
        id: "midi.quantize",
        label: "Quantize",
        accelerator: "Q",
        icon: "align-start-vertical",
        action: "midi:quantize",
        description: "Snap selected (or all) notes to the grid",
      },
      {
        type: "separator",
        id: "midi.sep.nudge",
      },
      {
        id: "midi.nudge_left",
        label: "Nudge Left",
        accelerator: "ArrowLeft",
        icon: "arrow-left",
        action: "midi:nudge-left",
        description: "Nudge selected notes one grid step earlier",
      },
      {
        id: "midi.nudge_right",
        label: "Nudge Right",
        accelerator: "ArrowRight",
        icon: "arrow-right",
        action: "midi:nudge-right",
        description: "Nudge selected notes one grid step later",
      },
      {
        type: "separator",
        id: "midi.sep.transpose",
      },
      {
        id: "midi.transpose_up",
        label: "Transpose Up",
        accelerator: "ArrowUp",
        icon: "arrow-up",
        action: "midi:transpose-up",
        description: "Transpose selected notes up one semitone",
      },
      {
        id: "midi.transpose_down",
        label: "Transpose Down",
        accelerator: "ArrowDown",
        icon: "arrow-down",
        action: "midi:transpose-down",
        description: "Transpose selected notes down one semitone",
      },
      {
        id: "midi.transpose_octave_up",
        label: "Transpose Up One Octave",
        accelerator: "Shift+ArrowUp",
        icon: "chevrons-up",
        action: "midi:transpose-octave-up",
        description: "Transpose selected notes up one octave",
      },
      {
        id: "midi.transpose_octave_down",
        label: "Transpose Down One Octave",
        accelerator: "Shift+ArrowDown",
        icon: "chevrons-down",
        action: "midi:transpose-octave-down",
        description: "Transpose selected notes down one octave",
      },
      {
        type: "separator",
        id: "midi.sep.devices",
      },
      {
        id: "midi.enable_devices",
        label: "Enable MIDI Devices",
        icon: "wifi",
        action: "midi:enable",
        description: "Request Web MIDI access and list connected MIDI devices",
      },
      {
        id: "midi.refresh_devices",
        label: "Refresh MIDI Devices",
        icon: "refresh-cw",
        action: "midi:refresh-devices",
        description: "Re-enumerate all connected MIDI inputs and outputs",
      },
    ],
  },

  {
    id: "project",
    label: "Project",
    children: [
      {
        id: "project.settings",
        label: "Project Settings...",
        accelerator: "Ctrl+.",
        icon: "settings-2",
        action: "project:settings",
      },
      {
        id: "project.rename",
        label: "Rename Project...",
        icon: "pencil",
        action: "project:rename",
      },
      {
        id: "project.tempo",
        label: "Tempo Settings...",
        icon: "gauge",
        action: "project:tempo-settings",
      },
      {
        id: "project.time_signature",
        label: "Time Signature...",
        icon: "music-2",
        action: "project:time-signature",
      },
      {
        id: "project.sample_rate",
        type: "submenu",
        label: "Sample Rate",
        icon: "activity",
        children: [
          {
            id: "project.sample_rate.44100",
            label: "44.1 kHz",
            action: "project:set-sample-rate-44100",
          },
          {
            id: "project.sample_rate.48000",
            label: "48 kHz",
            checked: true,
            action: "project:set-sample-rate-48000",
          },
          {
            id: "project.sample_rate.88200",
            label: "88.2 kHz",
            action: "project:set-sample-rate-88200",
          },
          {
            id: "project.sample_rate.96000",
            label: "96 kHz",
            action: "project:set-sample-rate-96000",
          },
          {
            id: "project.sample_rate.192000",
            label: "192 kHz",
            action: "project:set-sample-rate-192000",
          },
        ],
      },
      {
        id: "project.bit_depth",
        type: "submenu",
        label: "Bit Depth",
        icon: "binary",
        children: [
          {
            id: "project.bit_depth.16",
            label: "16-bit",
            action: "project:set-bit-depth-16",
          },
          {
            id: "project.bit_depth.24",
            label: "24-bit",
            checked: true,
            action: "project:set-bit-depth-24",
          },
          {
            id: "project.bit_depth.32float",
            label: "32-bit Float",
            action: "project:set-bit-depth-32float",
          },
        ],
      },
      {
        type: "separator",
        id: "project.sep.tracks",
      },
      {
        id: "project.add_audio_track",
        label: "Add Audio Track",
        accelerator: "Ctrl+T",
        icon: "mic",
        action: "track:add-audio",
      },
      {
        id: "project.add_midi_track",
        label: "Add MIDI Track",
        accelerator: "Ctrl+Shift+T",
        icon: "piano",
        action: "track:add-midi",
        description: "Add a new MIDI track routed to All MIDI Inputs",
      },
      {
        id: "project.add_plugin_track",
        label: "Add Plugin Track",
        icon: "cpu",
        action: "track:add-plugin",
        enabled: false,
      },
      {
        id: "project.add_bus_track",
        label: "Add Bus Track",
        icon: "route",
        action: "track:add-bus",
      },
      {
        id: "project.add_return_track",
        label: "Add Return Track",
        icon: "corner-down-left",
        action: "track:add-return",
      },
      {
        id: "project.add_master_bus",
        label: "Add Master Bus",
        icon: "speaker",
        action: "track:add-master-bus",
        enabled: false,
      },
      {
        type: "separator",
        id: "project.sep.track_actions",
      },
      {
        id: "project.duplicate_track",
        label: "Duplicate Track",
        icon: "copy-plus",
        action: "track:duplicate",
      },
      {
        id: "project.rename_track",
        label: "Rename Track",
        icon: "pencil",
        action: "track:rename",
      },
      {
        id: "project.color_track",
        label: "Change Track Color...",
        icon: "palette",
        action: "track:change-color",
      },
      {
        id: "project.freeze_track",
        label: "Freeze Track",
        icon: "snowflake",
        action: "track:freeze",
      },
      {
        id: "project.flatten_track",
        label: "Flatten Track",
        icon: "layers-2",
        action: "track:flatten",
      },
      {
        id: "project.delete_track",
        label: "Delete Track",
        icon: "trash-2",
        danger: true,
        action: "track:delete",
      },
      {
        type: "separator",
        id: "project.sep.markers",
      },
      {
        id: "project.add_marker",
        label: "Add Marker",
        accelerator: "M",
        icon: "map-pin",
        action: "marker:add",
      },
      {
        id: "project.next_marker",
        label: "Next Marker",
        icon: "skip-forward",
        action: "marker:next",
      },
      {
        id: "project.previous_marker",
        label: "Previous Marker",
        icon: "skip-back",
        action: "marker:previous",
      },
      {
        id: "project.marker_manager",
        label: "Marker Manager...",
        icon: "list",
        action: "marker:manager",
      },
      {
        type: "separator",
        id: "project.sep.clean",
      },
      {
        id: "project.collect_all_and_save",
        label: "Collect All and Save",
        icon: "package",
        action: "project:collect-all-and-save",
      },
      {
        id: "project.clean_unused_files",
        label: "Clean Unused Files...",
        icon: "sparkles",
        action: "project:clean-unused-files",
      },
      {
        id: "project.project_statistics",
        label: "Project Statistics...",
        icon: "bar-chart-3",
        action: "project:statistics",
      },
    ],
  },

  {
    id: "audio",
    label: "Audio",
    children: [
      {
        id: "audio.play_pause",
        label: "Play / Pause",
        accelerator: "Space",
        icon: "play",
        action: "transport:play-pause",
      },
      {
        id: "audio.stop",
        label: "Stop",
        accelerator: "Shift+Space",
        icon: "square",
        action: "transport:stop",
      },
      {
        id: "audio.record",
        label: "Record",
        accelerator: "R",
        icon: "circle",
        action: "transport:record",
        enabled: false,
      },
      {
        id: "audio.loop",
        label: "Loop",
        accelerator: "L",
        icon: "repeat",
        checked: false,
        action: "transport:toggle-loop",
      },
      {
        id: "audio.metronome",
        label: "Metronome",
        accelerator: "K",
        icon: "timer",
        checked: false,
        action: "transport:toggle-metronome",
      },
      {
        id: "audio.count_in",
        label: "Count-In",
        icon: "badge-123",
        checked: false,
        action: "transport:toggle-count-in",
      },
      {
        type: "separator",
        id: "audio.sep.navigation",
      },
      {
        id: "audio.go_to_start",
        label: "Go to Start",
        accelerator: "Home",
        icon: "step-back",
        action: "transport:go-to-start",
      },
      {
        id: "audio.go_to_end",
        label: "Go to End",
        accelerator: "End",
        icon: "step-forward",
        action: "transport:go-to-end",
      },
      {
        id: "audio.rewind",
        label: "Rewind",
        accelerator: "Alt+Left",
        icon: "rewind",
        action: "transport:rewind",
      },
      {
        id: "audio.fast_forward",
        label: "Fast Forward",
        accelerator: "Alt+Right",
        icon: "fast-forward",
        action: "transport:fast-forward",
      },
      {
        type: "separator",
        id: "audio.sep.clip",
      },
      {
        id: "audio.normalize_clip",
        label: "Normalize Clip",
        icon: "waves",
        action: "audio:normalize-clip",
      },
      {
        id: "audio.reverse_clip",
        label: "Reverse Clip",
        icon: "refresh-ccw",
        action: "audio:reverse-clip",
      },
      {
        id: "audio.fade_in",
        label: "Add Fade In",
        icon: "move-up-right",
        action: "audio:add-fade-in",
      },
      {
        id: "audio.fade_out",
        label: "Add Fade Out",
        icon: "move-down-right",
        action: "audio:add-fade-out",
      },
      {
        id: "audio.crossfade",
        label: "Create Crossfade",
        accelerator: "X",
        icon: "blend",
        action: "audio:create-crossfade",
      },
      {
        id: "audio.clip_gain",
        label: "Clip Gain...",
        icon: "volume-2",
        action: "audio:clip-gain",
      },
      {
        type: "separator",
        id: "audio.sep.render",
      },
      {
        id: "audio.bounce_in_place",
        label: "Bounce in Place",
        accelerator: "Ctrl+B",
        icon: "disc-3",
        action: "audio:bounce-in-place",
      },
      {
        id: "audio.render_selection",
        label: "Render Audio",
        accelerator: "Ctrl+R",
        icon: "box",
        action: "audio:render-selection",
      },
      {
        id: "audio.freeze_selected_tracks",
        label: "Freeze Selected Tracks",
        icon: "snowflake",
        action: "audio:freeze-selected-tracks",
      },
      {
        type: "separator",
        id: "audio.sep.devices",
      },
      {
        id: "audio.enable_input",
        label: "Enable Audio Input",
        icon: "mic",
        action: "audio:enable-input",
        description: "Request microphone permission and enumerate audio devices",
      },
      {
        id: "audio.refresh_devices",
        label: "Refresh Audio Devices",
        icon: "refresh-cw",
        action: "audio:refresh-devices",
        description: "Re-enumerate all connected audio input and output devices",
      },
      {
        type: "separator",
        id: "audio.sep.engine",
      },
      {
        id: "audio.audio_settings",
        label: "Audio Settings...",
        icon: "sliders-horizontal",
        action: "audio:settings",
      },
      {
        id: "audio.device",
        type: "submenu",
        label: "Audio Device",
        icon: "speaker",
        children: [
          {
            id: "audio.device.default",
            label: "System Default",
            checked: true,
            action: "audio:set-device-default",
          },
          {
            id: "audio.device.web_audio",
            label: "Web Audio",
            action: "audio:set-device-web-audio",
          },
          {
            id: "audio.device.native",
            label: "Sphere Native Audio",
            action: "audio:set-device-native",
            enabled: false,
          },
        ],
      },
      {
        id: "audio.buffer_size",
        type: "submenu",
        label: "Buffer Size",
        icon: "cpu",
        children: [
          {
            id: "audio.buffer_size.64",
            label: "64 samples",
            action: "audio:set-buffer-64",
            enabled: false,
          },
          {
            id: "audio.buffer_size.128",
            label: "128 samples",
            action: "audio:set-buffer-128",
            enabled: false,
          },
          {
            id: "audio.buffer_size.256",
            label: "256 samples",
            checked: true,
            action: "audio:set-buffer-256",
          },
          {
            id: "audio.buffer_size.512",
            label: "512 samples",
            action: "audio:set-buffer-512",
          },
          {
            id: "audio.buffer_size.1024",
            label: "1024 samples",
            action: "audio:set-buffer-1024",
          },
        ],
      },
      {
        type: "separator",
        id: "audio.sep.plugins",
      },
      {
        id: "audio.scan_plugins",
        label: "Scan Plugins",
        icon: "search",
        action: "plugins:scan",
        enabled: false,
      },
      {
        id: "audio.plugin_manager",
        label: "Plugin Manager...",
        icon: "blocks",
        action: "plugins:manager",
        enabled: false,
      },
      {
        id: "audio.supported_plugin_formats",
        type: "submenu",
        label: "Supported Plugin Formats",
        icon: "plug",
        children: [
          {
            id: "audio.plugins.vst3",
            label: "VST3",
            checked: true,
            action: "plugins:format-vst3",
            enabled: false,
          },
          {
            id: "audio.plugins.clap",
            label: "CLAP",
            checked: true,
            action: "plugins:format-clap",
            enabled: false,
          },
          {
            id: "audio.plugins.daux",
            label: "DAUx",
            action: "plugins:format-daux",
            enabled: false,
          },
        ],
      },
    ],
  },

  {
    id: "automation",
    label: "Automation",
    children: [
      {
        id: "automation.add_volume_lane",
        label: "Add Volume Automation",
        icon: "volume-2",
        action: "automation:add-volume-lane",
        description: "Add a volume automation lane to the selected track",
      },
      {
        id: "automation.add_pan_lane",
        label: "Add Pan Automation",
        icon: "blend",
        action: "automation:add-pan-lane",
        description: "Add a pan automation lane to the selected track",
      },
      {
        type: "separator" as const,
        id: "automation.sep.points",
      },
      {
        id: "automation.delete_selected_points",
        label: "Delete Selected Points",
        accelerator: "Delete",
        icon: "trash-2",
        danger: true,
        action: "automation:delete-selected-points",
      },
      {
        id: "automation.clear_lane",
        label: "Clear Selected Lane",
        icon: "eraser",
        action: "automation:clear-lane",
      },
      {
        type: "separator" as const,
        id: "automation.sep.curve",
      },
      {
        id: "automation.curve_linear",
        label: "Curve: Linear",
        icon: "trending-up",
        action: "automation:set-curve-linear",
      },
      {
        id: "automation.curve_hold",
        label: "Curve: Hold",
        icon: "step-forward",
        action: "automation:set-curve-hold",
      },
      {
        type: "separator" as const,
        id: "automation.sep.mode",
      },
      {
        id: "automation.mode",
        type: "submenu" as const,
        label: "Automation Mode",
        icon: "activity",
        children: [
          {
            id: "automation.mode.off",
            label: "Off",
            checked: true,
            action: "automation:set-mode-off",
          },
          {
            id: "automation.mode.read",
            label: "Read",
            action: "automation:set-mode-read",
          },
          {
            id: "automation.mode.touch",
            label: "Touch",
            enabled: false,
            action: "automation:set-mode-touch",
          },
          {
            id: "automation.mode.latch",
            label: "Latch",
            enabled: false,
            action: "automation:set-mode-latch",
          },
          {
            id: "automation.mode.write",
            label: "Write",
            enabled: false,
            action: "automation:set-mode-write",
          },
        ],
      },
    ],
  },

  {
    id: "window",
    label: "Window",
    children: [
      {
        id: "window.minimize",
        label: "Minimize",
        accelerator: "Ctrl+M",
        icon: "minus",
        role: "minimize",
        action: "window:minimize",
      },
      {
        id: "window.maximize",
        label: "Maximize",
        icon: "maximize",
        action: "window:maximize",
      },
      {
        id: "window.fullscreen",
        label: "Toggle Full Screen",
        accelerator: "F11",
        icon: "maximize-2",
        action: "window:toggle-fullscreen",
      },
      {
        id: "window.always_on_top",
        label: "Always on Top",
        icon: "pin",
        checked: false,
        action: "window:toggle-always-on-top",
      },
      {
        type: "separator",
        id: "window.sep.workspace",
      },
      {
        id: "window.show_browser",
        label: "Show Browser",
        accelerator: "Ctrl+1",
        icon: "folder",
        checked: true,
        action: "panel:toggle-browser",
      },
      {
        id: "window.show_inspector",
        label: "Show Inspector",
        accelerator: "Ctrl+2",
        icon: "panel-right",
        checked: true,
        action: "panel:toggle-inspector",
      },
      {
        id: "window.show_mixer",
        label: "Show Mixer",
        accelerator: "Ctrl+3",
        icon: "sliders-horizontal",
        checked: true,
        action: "panel:toggle-mixer",
      },
      {
        id: "window.show_device_panel",
        label: "Show Device Panel",
        accelerator: "Ctrl+4",
        icon: "blocks",
        checked: false,
        action: "panel:toggle-device-panel",
      },
      {
        id: "window.show_midi_editor",
        label: "Show MIDI Editor",
        accelerator: "Ctrl+5",
        icon: "piano",
        checked: false,
        action: "panel:toggle-midi-editor",
        enabled: false,
      },
      {
        id: "window.show_automation",
        label: "Show Automation",
        accelerator: "Ctrl+6",
        icon: "workflow",
        checked: false,
        action: "panel:toggle-automation",
      },
      {
        type: "separator",
        id: "window.sep.dock",
      },
      {
        id: "window.dock_browser",
        type: "submenu",
        label: "Dock Browser",
        icon: "panel-left",
        children: [
          {
            id: "window.dock_browser.left",
            label: "Dock Left",
            checked: true,
            action: "panel:browser-dock-left",
          },
          {
            id: "window.dock_browser.right",
            label: "Dock Right",
            action: "panel:browser-dock-right",
          },
          {
            id: "window.dock_browser.bottom",
            label: "Dock Bottom",
            action: "panel:browser-dock-bottom",
          },
          {
            id: "window.dock_browser.float",
            label: "Float",
            action: "panel:browser-float",
          },
        ],
      },
      {
        id: "window.dock_inspector",
        type: "submenu",
        label: "Dock Inspector",
        icon: "panel-right",
        children: [
          {
            id: "window.dock_inspector.left",
            label: "Dock Left",
            action: "panel:inspector-dock-left",
          },
          {
            id: "window.dock_inspector.right",
            label: "Dock Right",
            checked: true,
            action: "panel:inspector-dock-right",
          },
          {
            id: "window.dock_inspector.bottom",
            label: "Dock Bottom",
            action: "panel:inspector-dock-bottom",
          },
          {
            id: "window.dock_inspector.float",
            label: "Float",
            action: "panel:inspector-float",
          },
        ],
      },
      {
        id: "window.dock_mixer",
        type: "submenu",
        label: "Dock Mixer",
        icon: "panel-bottom",
        children: [
          {
            id: "window.dock_mixer.left",
            label: "Dock Left",
            action: "panel:mixer-dock-left",
          },
          {
            id: "window.dock_mixer.right",
            label: "Dock Right",
            action: "panel:mixer-dock-right",
          },
          {
            id: "window.dock_mixer.bottom",
            label: "Dock Bottom",
            checked: true,
            action: "panel:mixer-dock-bottom",
          },
          {
            id: "window.dock_mixer.float",
            label: "Float",
            action: "panel:mixer-float",
          },
        ],
      },
      {
        type: "separator",
        id: "window.sep.zoom",
      },
      {
        id: "window.zoom_in",
        label: "Zoom In",
        accelerator: "Ctrl+=",
        icon: "zoom-in",
        action: "view:zoom-in",
      },
      {
        id: "window.zoom_out",
        label: "Zoom Out",
        accelerator: "Ctrl+-",
        icon: "zoom-out",
        action: "view:zoom-out",
      },
      {
        id: "window.reset_zoom",
        label: "Reset Zoom",
        accelerator: "Ctrl+0",
        icon: "scan",
        action: "view:reset-zoom",
      },
      {
        type: "separator",
        id: "window.sep.layouts",
      },
      {
        id: "window.workspace_layouts",
        type: "submenu",
        label: "Workspace Layouts",
        icon: "layout-dashboard",
        children: [
          {
            id: "window.layout.default",
            label: "Default",
            checked: true,
            action: "layout:default",
          },
          {
            id: "window.layout.editing",
            label: "Editing",
            action: "layout:editing",
          },
          {
            id: "window.layout.mixing",
            label: "Mixing",
            action: "layout:mixing",
          },
          {
            id: "window.layout.sound_design",
            label: "Sound Design",
            action: "layout:sound-design",
          },
          {
            id: "window.layout.minimal",
            label: "Minimal",
            action: "layout:minimal",
          },
          {
            id: "window.layout.laptop",
            label: "Laptop",
            action: "layout:laptop",
          },
          {
            id: "window.layout.reset",
            label: "Reset Current Layout",
            action: "layout:reset-current",
          },
        ],
      },
    ],
  },

  {
    id: "tools",
    label: "Tools",
    children: [
      {
        id: "tools.select_pointer",
        label: "Pointer Tool",
        accelerator: "V",
        icon: "pointer",
        action: "tools:select-pointer",
        description: "Select and move clips",
      },
      {
        id: "tools.select_pen",
        label: "Pen Tool",
        accelerator: "P",
        icon: "pen",
        action: "tools:select-pen",
        description: "Draw new clips",
      },
      {
        id: "tools.select_cut",
        label: "Cut Tool",
        accelerator: "C",
        icon: "scissors",
        action: "tools:select-cut",
        description: "Split clips",
      },
      {
        id: "tools.select_glue",
        label: "Glue Tool",
        accelerator: "G",
        icon: "combine",
        action: "tools:select-glue",
        description: "Join adjacent clips",
      },
      {
        id: "tools.select_mute",
        label: "Mute Tool",
        icon: "volume-x",
        action: "tools:select-mute",
        description: "Toggle clip mute",
      },
      {
        id: "tools.select_time",
        label: "Time Tool",
        accelerator: "T",
        icon: "move-horizontal",
        action: "tools:select-time",
        description: "Time-stretch clips",
      },
      {
        id: "tools.select_automation",
        label: "Automation Tool",
        accelerator: "A",
        icon: "activity",
        action: "tools:select-automation",
        description: "Edit automation lanes",
      },
      {
        type: "separator",
        id: "tools.sep.tools_end",
      },
      {
        id: "tools.command_palette",
        label: "Command Palette...",
        accelerator: "Ctrl+K",
        icon: "terminal",
        action: "tools:command-palette",
      },
      {
        id: "tools.quick_search",
        label: "Quick Search...",
        accelerator: "Ctrl+P",
        icon: "search",
        action: "tools:quick-search",
      },
      {
        type: "separator",
        id: "tools.sep.audio_tools",
      },
      {
        id: "tools.audio_analyzer",
        label: "Audio Analyzer",
        icon: "activity",
        action: "tools:audio-analyzer",
      },
      {
        id: "tools.loudness_meter",
        label: "Loudness Meter",
        icon: "gauge",
        action: "tools:loudness-meter",
      },
      {
        id: "tools.spectrum_analyzer",
        label: "Spectrum Analyzer",
        icon: "bar-chart-4",
        action: "tools:spectrum-analyzer",
      },
      {
        id: "tools.phase_meter",
        label: "Phase Meter",
        icon: "orbit",
        action: "tools:phase-meter",
      },
      {
        id: "tools.tuner",
        label: "Tuner",
        icon: "guitar",
        action: "tools:tuner",
        enabled: false,
      },
      {
        type: "separator",
        id: "tools.sep.project_tools",
      },
      {
        id: "tools.media_pool",
        label: "Media Pool",
        icon: "database",
        action: "tools:media-pool",
      },
      {
        id: "tools.sample_browser",
        label: "Sample Browser",
        icon: "folder-search",
        action: "tools:sample-browser",
      },
      {
        id: "tools.loop_browser",
        label: "Loop Browser",
        icon: "repeat-2",
        action: "tools:loop-browser",
      },
      {
        id: "tools.marker_list",
        label: "Marker List",
        icon: "list",
        action: "tools:marker-list",
      },
      {
        type: "separator",
        id: "tools.sep.midi",
      },
      {
        id: "tools.midi_monitor",
        label: "MIDI Monitor",
        icon: "radio",
        action: "tools:midi-monitor",
        enabled: false,
      },
      {
        id: "tools.midi_mapping",
        label: "MIDI Mapping...",
        icon: "keyboard-music",
        action: "tools:midi-mapping",
        enabled: false,
      },
      {
        id: "tools.controller_setup",
        label: "Controller Setup...",
        icon: "gamepad-2",
        action: "tools:controller-setup",
        enabled: false,
      },
      {
        type: "separator",
        id: "tools.sep.native",
      },
      {
        id: "tools.sphere_engine_console",
        label: "SphereEngine Console",
        icon: "cpu",
        action: "tools:sphere-engine-console",
        enabled: false,
      },
      {
        id: "tools.daux_sdk",
        label: "DAUx SDK Tools",
        icon: "plug-zap",
        action: "tools:daux-sdk",
        enabled: false,
      },
      {
        id: "tools.plugin_sandbox",
        label: "Plugin Sandbox",
        icon: "shield",
        action: "tools:plugin-sandbox",
        enabled: false,
      },
      {
        type: "separator",
        id: "tools.sep.developer",
      },
      {
        id: "tools.developer_tools",
        label: "Developer Tools",
        accelerator: "Ctrl+Shift+I",
        icon: "bug",
        action: "tools:developer-tools",
      },
      {
        id: "tools.reload_window",
        label: "Reload Window",
        icon: "refresh-cw",
        action: "app:reload",
      },
      {
        id: "tools.force_reload_window",
        label: "Force Reload Window",
        accelerator: "Ctrl+Shift+R",
        icon: "refresh-ccw",
        action: "app:force-reload",
      },
      {
        id: "tools.performance_monitor",
        label: "Performance Monitor",
        icon: "monitor-dot",
        action: "tools:performance-monitor",
      },
    ],
  },

  {
    id: "help",
    label: "Help",
    children: [
      {
        id: "help.quick_start",
        label: "Quick Start Guide",
        icon: "book-open",
        action: "help:quick-start",
      },
      {
        id: "help.documentation",
        label: "Documentation",
        accelerator: "F1",
        icon: "book",
        action: "help:documentation",
      },
      {
        id: "help.keyboard_shortcuts",
        label: "Keyboard Shortcuts",
        accelerator: "Ctrl+/",
        icon: "keyboard",
        action: "help:keyboard-shortcuts",
      },
      {
        id: "help.release_notes",
        label: "Release Notes",
        icon: "newspaper",
        action: "help:release-notes",
      },
      {
        id: "help.roadmap",
        label: "Roadmap",
        icon: "map",
        action: "help:roadmap",
      },
      {
        type: "separator",
        id: "help.sep.community",
      },
      {
        id: "help.github",
        label: "GitHub Repository",
        icon: "github",
        action: "help:github",
      },
      {
        id: "help.report_issue",
        label: "Report Issue",
        icon: "circle-alert",
        action: "help:report-issue",
      },
      {
        id: "help.request_feature",
        label: "Request Feature",
        icon: "sparkles",
        action: "help:request-feature",
      },
      {
        id: "help.community",
        label: "Community",
        icon: "messages-square",
        action: "help:community",
      },
      {
        type: "separator",
        id: "help.sep.support",
      },
      {
        id: "help.check_for_updates",
        label: "Check for Updates...",
        icon: "download-cloud",
        action: "app:check-for-updates",
      },
      {
        id: "help.diagnostics",
        label: "Diagnostics...",
        icon: "stethoscope",
        action: "help:diagnostics",
      },
      {
        id: "help.copy_system_info",
        label: "Copy System Info",
        icon: "clipboard-copy",
        action: "help:copy-system-info",
      },
      {
        type: "separator",
        id: "help.sep.about",
      },
      {
        id: "help.about",
        label: "About Futureboard Studio",
        icon: "info",
        action: "app:about",
      },
    ],
  },
];
